$axure.loadCurrentPage({
  "url":"vacancy.html",
  "generationDate":new Date(1399457453404.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"aa1df93e0b38467c97539eaa999c80ca",
    "type":"Axure:Page",
    "name":"Vacancy",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a17996ca81c45e491c8f98a37d703fd",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"e1b6dfa2e93d4059aa8d934d5cae5423",
          "label":"menu_left",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":190,
              "height":1110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"43e2b71c707941248571b844b4f1c484",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5e8fddcf84854b8e85d9f16f1135f67f",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":190,
                      "height":1140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b3b29e565574ba3851ca3cf4e6cf142",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":190,
                          "height":1140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"dd24935de1c041f3a1651bf40304df2b",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":276},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c8cfe889535435780dbf5cfdd780f8b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":276},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"d69660317d374f1c80d9f3e3c86de526",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":179},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21e369a024334d8e8a229752567acdaa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":179},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"30625acf17284eb3881e9c28c7fad2d2",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":133},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc35cf650bc6416094f87b3e370c90e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":133},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"0b28374f43db4e78ae5a9824b5b542b9",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":320},
                    "size":{
                      "width":108,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca54171ced09432e9c5d839f3e961727",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":320},
                        "size":{
                          "width":108,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f7c9262035ee421cb4f652e6440a4730",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":25},
                    "size":{
                      "width":163,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4afc510f4c1b4705ba5ec15394f078af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":25},
                        "size":{
                          "width":163,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u28.png"}},
{
                  "id":"a34508b0f5634a1ebe0389e45ee2a1e0",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":228},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7773d06475e14d1583f0bdb7ad32258d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":228},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"24ca6061848c4d499112dd3e8e285dbd",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":122,
                      "y":315},
                    "size":{
                      "width":18,
                      "height":18},
                    "rotation":"270",
                    "textRotation":"270",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"36dbc1462f85408d9a7e569dbe321bfa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":122,
                          "y":315},
                        "size":{
                          "width":18,
                          "height":18},
                        "rotation":"270",
                        "textRotation":"270",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u35.png"}},
{
                  "id":"521b2365f4c147c9b0a40fe9607d6d06",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":127,
                      "y":316},
                    "size":{
                      "width":8,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b236bd8d5f54aa98909281c47d05f7f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":127,
                          "y":316},
                        "size":{
                          "width":8,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4a00fd8438b749b5b598251c1b7ee43c",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":512},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"119ba9355d7d44fdb4acc6c72f8d9428",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":512},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Vacancy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"vacancy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"d38608a796bd4e1cba63f829f255ad25",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":471},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"015c53ea6ed84e84abc2e530e8e62768",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":471},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Company in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"company.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"0ff9592219ed4b5096e4ab8261b56a06",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":594},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"5ed1339716ee4cfeb3dbcd8e2ee61151",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"75f0e6a821454e41acb32990070028ef",
                          "label":"",
                          "parentDynamicPanel":"0ff9592219ed4b5096e4ab8261b56a06",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":139,
                              "height":63}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"523c8bc329b34985824f320a0e7aefd1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"0ff9592219ed4b5096e4ab8261b56a06",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":139,
                                  "height":63}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/index/u31.png"}}]}]},
{
                  "id":"e9f343ea1f724167aa11926009e0b6c0",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":429},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af75effd89ef479484626c1524f630c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":429},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Spravochnik in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"spravochnik.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"591a16e220bb463388827befe782a5a9",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":388},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3838a2e4fce64c9bb1e2a71dc9629e2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":388},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Calculator in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"calculator.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"9922141dd4ea4202a12ca08da47a8b16",
                  "label":"",
                  "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":553},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee77320d520045c3a842c41ad2107ebd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e1b6dfa2e93d4059aa8d934d5cae5423",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":553},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Contacts_1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"contacts_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"953634dc3eea4c149a44015613767cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":93},
            "size":{
              "width":236,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88cc60f17e3d414c92449c335c06c5ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":93},
                "size":{
                  "width":236,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa9fcb9771e54af3812aaaa8afa0c815",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":150},
            "size":{
              "width":730,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74b687e6be1d4c1ca146976b4c2c4818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":150},
                "size":{
                  "width":730,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u4.png"}},
{
          "id":"d2204e6f7a494347b395f8c1f17073e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":230,
              "y":638},
            "size":{
              "width":190,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0569bf78f3f7444c912558ed38093bbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":230,
                  "y":638},
                "size":{
                  "width":190,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c7e171c0f9749568dbf71b0d8ff0e38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":478,
              "y":638},
            "size":{
              "width":190,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf57dea9af454bcd845da4c55cfb9f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":478,
                  "y":638},
                "size":{
                  "width":190,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47c2b523335f41bb96a33ec70ffc0e32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":478,
              "y":685},
            "size":{
              "width":227,
              "height":185}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260cc90ab0f549c88f283bba85448930",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":478,
                  "y":685},
                "size":{
                  "width":227,
                  "height":185}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ad5cfe78ad34742b921d87016caaf09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":732,
              "y":639},
            "size":{
              "width":190,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d0496591fef4f579c7a1b2386733405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":732,
                  "y":639},
                "size":{
                  "width":190,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96a02f99bdbd4431ba283f5d4b01fa98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":733,
              "y":686},
            "size":{
              "width":227,
              "height":184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2f8da8d18354c69afaa035a6021326a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":733,
                  "y":686},
                "size":{
                  "width":227,
                  "height":184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cefa765412894ef49e6a954549c93d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":686},
            "size":{
              "width":227,
              "height":169}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e82a3061b9418bbff9e865632a50ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":686},
                "size":{
                  "width":227,
                  "height":169}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60833c3b25f941209a88d7a653df2b05",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1084},
            "size":{
              "width":318,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee84a43e25764cf9b18122901bb03152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1084},
                "size":{
                  "width":318,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01ba2bc598ce41eb89ecd801b69fbc66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":230,
              "y":1171},
            "size":{
              "width":370,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7e3de40e8d4979a432b44264796754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":230,
                  "y":1171},
                "size":{
                  "width":370,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Vacancy_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vacancy_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cf14e8c80c54e808b2854aa68ed87ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":230,
              "y":1221},
            "size":{
              "width":390,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c335ef3d47744e6a84a131a6dc26bee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":230,
                  "y":1221},
                "size":{
                  "width":390,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Vacancy_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vacancy_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29ae4d5e45134bab99e4f903fe72e292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":230,
              "y":1271},
            "size":{
              "width":335,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9faa5ad0f1bd4b2397b36af8ccd813f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":230,
                  "y":1271},
                "size":{
                  "width":335,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Vacancy_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vacancy_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec8a21df63104b8d83aab28ec0ebd186",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":376,
              "y":921},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3faff4da13c4afc9531a6dd1eb48e43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":376,
                  "y":921},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/spravochnik/u59.png"}},
{
          "id":"237172e61ac84ec2bfac85802158492e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":939},
            "size":{
              "width":370,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b19a682663e48b0964e36544715b917",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":939},
                "size":{
                  "width":370,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69d60e1ceba6454eb99fa45c9b31170e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1660},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c16a64200de4fd3987ea7aa90a90693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1660},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u67.png"}},
{
          "id":"cb695ebe2a8e4cac803b8cca7f1c70ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "underline":true,
            "location":{
              "x":229,
              "y":1322},
            "size":{
              "width":141,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5794a35aa1e847168ff55bdbbe469679",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "underline":true,
                "location":{
                  "x":229,
                  "y":1322},
                "size":{
                  "width":141,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Vacancy_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vacancy_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "4a17996ca81c45e491c8f98a37d703fd":{
      "scriptId":"u0",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u1"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u2"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u3"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u4"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u5"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u6"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u7"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u8"}},
    "e1b6dfa2e93d4059aa8d934d5cae5423":{
      "scriptId":"u9"},
    "5e8fddcf84854b8e85d9f16f1135f67f":{
      "scriptId":"u10"},
    "7b3b29e565574ba3851ca3cf4e6cf142":{
      "scriptId":"u11"},
    "dd24935de1c041f3a1651bf40304df2b":{
      "scriptId":"u12"},
    "6c8cfe889535435780dbf5cfdd780f8b":{
      "scriptId":"u13"},
    "d69660317d374f1c80d9f3e3c86de526":{
      "scriptId":"u14"},
    "21e369a024334d8e8a229752567acdaa":{
      "scriptId":"u15"},
    "30625acf17284eb3881e9c28c7fad2d2":{
      "scriptId":"u16"},
    "dc35cf650bc6416094f87b3e370c90e0":{
      "scriptId":"u17"},
    "0b28374f43db4e78ae5a9824b5b542b9":{
      "scriptId":"u18"},
    "ca54171ced09432e9c5d839f3e961727":{
      "scriptId":"u19"},
    "f7c9262035ee421cb4f652e6440a4730":{
      "scriptId":"u20"},
    "4afc510f4c1b4705ba5ec15394f078af":{
      "scriptId":"u21"},
    "a34508b0f5634a1ebe0389e45ee2a1e0":{
      "scriptId":"u22"},
    "7773d06475e14d1583f0bdb7ad32258d":{
      "scriptId":"u23"},
    "24ca6061848c4d499112dd3e8e285dbd":{
      "scriptId":"u24"},
    "36dbc1462f85408d9a7e569dbe321bfa":{
      "scriptId":"u25"},
    "521b2365f4c147c9b0a40fe9607d6d06":{
      "scriptId":"u26"},
    "8b236bd8d5f54aa98909281c47d05f7f":{
      "scriptId":"u27"},
    "4a00fd8438b749b5b598251c1b7ee43c":{
      "scriptId":"u28"},
    "119ba9355d7d44fdb4acc6c72f8d9428":{
      "scriptId":"u29"},
    "d38608a796bd4e1cba63f829f255ad25":{
      "scriptId":"u30"},
    "015c53ea6ed84e84abc2e530e8e62768":{
      "scriptId":"u31"},
    "0ff9592219ed4b5096e4ab8261b56a06":{
      "scriptId":"u32"},
    "75f0e6a821454e41acb32990070028ef":{
      "scriptId":"u33"},
    "523c8bc329b34985824f320a0e7aefd1":{
      "scriptId":"u34"},
    "e9f343ea1f724167aa11926009e0b6c0":{
      "scriptId":"u35"},
    "af75effd89ef479484626c1524f630c8":{
      "scriptId":"u36"},
    "591a16e220bb463388827befe782a5a9":{
      "scriptId":"u37"},
    "3838a2e4fce64c9bb1e2a71dc9629e2a":{
      "scriptId":"u38"},
    "9922141dd4ea4202a12ca08da47a8b16":{
      "scriptId":"u39"},
    "ee77320d520045c3a842c41ad2107ebd":{
      "scriptId":"u40"},
    "953634dc3eea4c149a44015613767cea":{
      "scriptId":"u41"},
    "88cc60f17e3d414c92449c335c06c5ea":{
      "scriptId":"u42"},
    "aa9fcb9771e54af3812aaaa8afa0c815":{
      "scriptId":"u43"},
    "74b687e6be1d4c1ca146976b4c2c4818":{
      "scriptId":"u44"},
    "d2204e6f7a494347b395f8c1f17073e4":{
      "scriptId":"u45"},
    "0569bf78f3f7444c912558ed38093bbc":{
      "scriptId":"u46"},
    "3c7e171c0f9749568dbf71b0d8ff0e38":{
      "scriptId":"u47"},
    "bf57dea9af454bcd845da4c55cfb9f9d":{
      "scriptId":"u48"},
    "47c2b523335f41bb96a33ec70ffc0e32":{
      "scriptId":"u49"},
    "260cc90ab0f549c88f283bba85448930":{
      "scriptId":"u50"},
    "5ad5cfe78ad34742b921d87016caaf09":{
      "scriptId":"u51"},
    "0d0496591fef4f579c7a1b2386733405":{
      "scriptId":"u52"},
    "96a02f99bdbd4431ba283f5d4b01fa98":{
      "scriptId":"u53"},
    "a2f8da8d18354c69afaa035a6021326a":{
      "scriptId":"u54"},
    "cefa765412894ef49e6a954549c93d7a":{
      "scriptId":"u55"},
    "e4e82a3061b9418bbff9e865632a50ec":{
      "scriptId":"u56"},
    "60833c3b25f941209a88d7a653df2b05":{
      "scriptId":"u57"},
    "ee84a43e25764cf9b18122901bb03152":{
      "scriptId":"u58"},
    "01ba2bc598ce41eb89ecd801b69fbc66":{
      "scriptId":"u59"},
    "6c7e3de40e8d4979a432b44264796754":{
      "scriptId":"u60"},
    "8cf14e8c80c54e808b2854aa68ed87ba":{
      "scriptId":"u61"},
    "5c335ef3d47744e6a84a131a6dc26bee":{
      "scriptId":"u62"},
    "29ae4d5e45134bab99e4f903fe72e292":{
      "scriptId":"u63"},
    "9faa5ad0f1bd4b2397b36af8ccd813f6":{
      "scriptId":"u64"},
    "ec8a21df63104b8d83aab28ec0ebd186":{
      "scriptId":"u65"},
    "a3faff4da13c4afc9531a6dd1eb48e43":{
      "scriptId":"u66"},
    "237172e61ac84ec2bfac85802158492e":{
      "scriptId":"u67"},
    "9b19a682663e48b0964e36544715b917":{
      "scriptId":"u68"},
    "69d60e1ceba6454eb99fa45c9b31170e":{
      "scriptId":"u69"},
    "2c16a64200de4fd3987ea7aa90a90693":{
      "scriptId":"u70"},
    "cb695ebe2a8e4cac803b8cca7f1c70ae":{
      "scriptId":"u71"},
    "5794a35aa1e847168ff55bdbbe469679":{
      "scriptId":"u72"}}});