$axure.loadCurrentPage({
  "url":"vacancy_page.html",
  "generationDate":new Date(1399457453658.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"89a1f87bec8049479a23e5111f2006bf",
    "type":"Axure:Page",
    "name":"Vacancy_page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7c4c06223194097820c470594d2155c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":130},
            "size":{
              "width":376,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42014ffd9544238a7c53e6287e40a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":130},
                "size":{
                  "width":376,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f240fef46e9945ca8c52545d11d931ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":80},
            "size":{
              "width":120,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9bd2cedc79422fb48eb302d00cb58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":80},
                "size":{
                  "width":120,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Vacancy in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"vacancy.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/vacancy_page/u2.png"}},
{
          "id":"ca8806f6cbdd4ae2b29b925011a4ef53",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
          "label":"menu_left",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":190,
              "height":1110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b03e7c1d90824fa4b47f032ddcb8faee",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"368263863e814b159c10c9d5a24d860a",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":190,
                      "height":1140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98da3ffdcaea4a50ae27f6649359b855",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":190,
                          "height":1140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"10a88ff6399d47a0a306c8db490bab2d",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":276},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbb190e58e334ac9ad61260d6706b60a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":276},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f0a126a01c1d482dae5fd764402ca89f",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":179},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"943efdde9c5245509a5c9455d2808b23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":179},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"c4d507d7efee4fb4b97c2dc0fe264016",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":133},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07065815eb7c481a9198dc30abe24862",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":133},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"50dfdb05d5404ba1ba69462a3992e594",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":320},
                    "size":{
                      "width":108,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9aa1275c0e7e4efa9cf675e3db8e3bd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":320},
                        "size":{
                          "width":108,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"205a90b14f2e4a57a6e515741bbee681",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":25},
                    "size":{
                      "width":163,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"610d2195b5d843649ba23e2b42077021",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":25},
                        "size":{
                          "width":163,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u28.png"}},
{
                  "id":"dab1689aff95418780f847a3615fc37e",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":228},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7544c56761924e5783fdf51ac1a9e0d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":228},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"77fc4f26ce0a473a86780fcb7885415c",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":122,
                      "y":315},
                    "size":{
                      "width":18,
                      "height":18},
                    "rotation":"270",
                    "textRotation":"270",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e651277358d64073b3b8825c728429eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":122,
                          "y":315},
                        "size":{
                          "width":18,
                          "height":18},
                        "rotation":"270",
                        "textRotation":"270",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u35.png"}},
{
                  "id":"5a7b62061b6e453c912393f1b2edd85b",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":127,
                      "y":316},
                    "size":{
                      "width":8,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88f5a2fcf7554d3a9ce34917aefbc1d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":127,
                          "y":316},
                        "size":{
                          "width":8,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f28420e224f3422d8839704a2778a1c5",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":512},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edf3b74e998249af860d21f1608bf397",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":512},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Vacancy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"vacancy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"455b6dcdf6e94b478b39261d2ebfbffe",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":471},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d16c76fa0df34826968b10cb0a3ad5d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":471},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Company in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"company.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"73f4a9c4994c4c81b30f78ebb004e85c",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":594},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"8f48d87c4e7e4c728bb02150bf96c8b5",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ef6bb60d58dc423f9d50f4bfba54c655",
                          "label":"",
                          "parentDynamicPanel":"73f4a9c4994c4c81b30f78ebb004e85c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":139,
                              "height":63}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7023cc9c66394ca7b78d076679b49efc",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"73f4a9c4994c4c81b30f78ebb004e85c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":139,
                                  "height":63}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/index/u31.png"}}]}]},
{
                  "id":"9ad1f8ec82814c86886155702d3fb282",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":429},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0199ba2ed124b01b3f5c0a887d84b79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":429},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Spravochnik in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"spravochnik.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"510488bdc09546fdb1c445b547f8f42a",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":388},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a9f115301a044e580a946b5fa5de465",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":388},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Calculator in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"calculator.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"c4f5d1f7691e464b86ffbe0796bd0488",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":553},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5b1ae0f55dc4d9d855c9240341be8d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":553},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Contacts_1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"contacts_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5ab57add58de46fc828f6211a9b322c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":249},
            "size":{
              "width":620,
              "height":406}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f2a287b21e41f1ac0099024ba85426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":249},
                "size":{
                  "width":620,
                  "height":406}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66ad7a90b67941c5a7ff939de95bb001",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":646},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb89ad77df1b4bdab551708c7be8e355",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":646},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"b2dfef17398941dca71a5410ff274967",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":237,
              "y":643},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e33378b24d04f83a30f6669266ae0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":237,
                  "y":643},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c6daab2e2254ff085ae584e5c5a1083",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":653},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1bd8efb3f714587bba5a5e7eda5a053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":653},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a592321a341747fdadac9120e79f00a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":847},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e607792a69e412dbb76cf56d33f3194",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":847},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u67.png"}}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "e7c4c06223194097820c470594d2155c":{
      "scriptId":"u0"},
    "a42014ffd9544238a7c53e6287e40a66":{
      "scriptId":"u1"},
    "f240fef46e9945ca8c52545d11d931ca":{
      "scriptId":"u2"},
    "cb9bd2cedc79422fb48eb302d00cb58c":{
      "scriptId":"u3"},
    "ca8806f6cbdd4ae2b29b925011a4ef53":{
      "scriptId":"u4",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u5"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u6"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u7"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u8"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u9"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u10"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u11"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u12"}},
    "dd43ce6f0eeb49ae9973a4432bfd5ee4":{
      "scriptId":"u13"},
    "368263863e814b159c10c9d5a24d860a":{
      "scriptId":"u14"},
    "98da3ffdcaea4a50ae27f6649359b855":{
      "scriptId":"u15"},
    "10a88ff6399d47a0a306c8db490bab2d":{
      "scriptId":"u16"},
    "fbb190e58e334ac9ad61260d6706b60a":{
      "scriptId":"u17"},
    "f0a126a01c1d482dae5fd764402ca89f":{
      "scriptId":"u18"},
    "943efdde9c5245509a5c9455d2808b23":{
      "scriptId":"u19"},
    "c4d507d7efee4fb4b97c2dc0fe264016":{
      "scriptId":"u20"},
    "07065815eb7c481a9198dc30abe24862":{
      "scriptId":"u21"},
    "50dfdb05d5404ba1ba69462a3992e594":{
      "scriptId":"u22"},
    "9aa1275c0e7e4efa9cf675e3db8e3bd8":{
      "scriptId":"u23"},
    "205a90b14f2e4a57a6e515741bbee681":{
      "scriptId":"u24"},
    "610d2195b5d843649ba23e2b42077021":{
      "scriptId":"u25"},
    "dab1689aff95418780f847a3615fc37e":{
      "scriptId":"u26"},
    "7544c56761924e5783fdf51ac1a9e0d8":{
      "scriptId":"u27"},
    "77fc4f26ce0a473a86780fcb7885415c":{
      "scriptId":"u28"},
    "e651277358d64073b3b8825c728429eb":{
      "scriptId":"u29"},
    "5a7b62061b6e453c912393f1b2edd85b":{
      "scriptId":"u30"},
    "88f5a2fcf7554d3a9ce34917aefbc1d7":{
      "scriptId":"u31"},
    "f28420e224f3422d8839704a2778a1c5":{
      "scriptId":"u32"},
    "edf3b74e998249af860d21f1608bf397":{
      "scriptId":"u33"},
    "455b6dcdf6e94b478b39261d2ebfbffe":{
      "scriptId":"u34"},
    "d16c76fa0df34826968b10cb0a3ad5d3":{
      "scriptId":"u35"},
    "73f4a9c4994c4c81b30f78ebb004e85c":{
      "scriptId":"u36"},
    "ef6bb60d58dc423f9d50f4bfba54c655":{
      "scriptId":"u37"},
    "7023cc9c66394ca7b78d076679b49efc":{
      "scriptId":"u38"},
    "9ad1f8ec82814c86886155702d3fb282":{
      "scriptId":"u39"},
    "d0199ba2ed124b01b3f5c0a887d84b79":{
      "scriptId":"u40"},
    "510488bdc09546fdb1c445b547f8f42a":{
      "scriptId":"u41"},
    "4a9f115301a044e580a946b5fa5de465":{
      "scriptId":"u42"},
    "c4f5d1f7691e464b86ffbe0796bd0488":{
      "scriptId":"u43"},
    "c5b1ae0f55dc4d9d855c9240341be8d4":{
      "scriptId":"u44"},
    "5ab57add58de46fc828f6211a9b322c6":{
      "scriptId":"u45"},
    "61f2a287b21e41f1ac0099024ba85426":{
      "scriptId":"u46"},
    "66ad7a90b67941c5a7ff939de95bb001":{
      "scriptId":"u47"},
    "cb89ad77df1b4bdab551708c7be8e355":{
      "scriptId":"u48"},
    "b2dfef17398941dca71a5410ff274967":{
      "scriptId":"u49"},
    "5e33378b24d04f83a30f6669266ae0ec":{
      "scriptId":"u50"},
    "1c6daab2e2254ff085ae584e5c5a1083":{
      "scriptId":"u51"},
    "c1bd8efb3f714587bba5a5e7eda5a053":{
      "scriptId":"u52"},
    "a592321a341747fdadac9120e79f00a9":{
      "scriptId":"u53"},
    "2e607792a69e412dbb76cf56d33f3194":{
      "scriptId":"u54"}}});