$axure.loadCurrentPage({
  "url":"news_page.html",
  "generationDate":new Date(1399457454323.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"deb98e50a6fe4e10bd7e1a1e89241560",
    "type":"Axure:Page",
    "name":"News_page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2abfea0f6aa64532bbe2efb1cadd3e35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":230,
              "y":229},
            "size":{
              "width":600,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"138f1ecb3ac7402db622ce9fb9d5ead4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":230,
                  "y":229},
                "size":{
                  "width":600,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7c4c06223194097820c470594d2155c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":130},
            "size":{
              "width":392,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42014ffd9544238a7c53e6287e40a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":130},
                "size":{
                  "width":392,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3924cecbfab48c3817462c006268381",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":230,
              "y":310},
            "size":{
              "width":730,
              "height":372},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da27a5ecf3ed474899284f7e85e085fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":230,
                  "y":310},
                "size":{
                  "width":730,
                  "height":372},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u4.png"}},
{
          "id":"0f89ca70652e417ea6dc119709f85056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":229,
              "y":707},
            "size":{
              "width":600,
              "height":723}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad6127ab708844a5b83c4d2ba3de1bc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":229,
                  "y":707},
                "size":{
                  "width":600,
                  "height":723}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e251aebd42c459dba58cc4f00f6727f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":1359},
            "size":{
              "width":451,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94ae4053419846d884cc29c0a312c318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":1359},
                "size":{
                  "width":451,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/news_page/u8.png"}},
{
          "id":"f240fef46e9945ca8c52545d11d931ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":80},
            "size":{
              "width":120,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9bd2cedc79422fb48eb302d00cb58c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":80},
                "size":{
                  "width":120,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_arhive in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_arhive.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/vacancy_page/u2.png"}},
{
          "id":"86bfe3a0f5b640bc9ab3c88b9ef446f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":1611},
            "size":{
              "width":320,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"969cf4d4996b43a9b9b70d5e14d754a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":1611},
                "size":{
                  "width":320,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"732072aa8b2547bab5d17b7d3d8ba3a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1557},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d409aec104d47c1a74006f66de7f1ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1557},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e908bfa5861d414daf0104825d666a3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":1833},
            "size":{
              "width":320,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0d08809f1649c6afbae9d1e99f157a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":1833},
                "size":{
                  "width":320,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5515293a4ecc4c96a61dc3932535f778",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1783},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c4184ea68a940a08c221e85cad1c558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1783},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c456392390649418dcac2f87f52a398",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1507},
            "size":{
              "width":730,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/news_page/u20_line.png"}},
{
          "id":"25c75a6cfedc4ab3845719cc769cdcc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":230,
              "y":1474},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82f6362344d4f299ba0b426596c6baf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":230,
                  "y":1474},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb86fb1a9f54482a892958aa1d3619e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":610,
              "y":1611},
            "size":{
              "width":320,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81802f99355c4e2ab9602f041db98ce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":610,
                  "y":1611},
                "size":{
                  "width":320,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb283f9b7e464292a8901d76f9bba1fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":1557},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2f8097a2f3b4a6288b9600b1e8d3bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":1557},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"051160ac027d4340ab9479e54765d2db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":610,
              "y":1833},
            "size":{
              "width":320,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e9d31a608b443f8377171c6bbc935e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":610,
                  "y":1833},
                "size":{
                  "width":320,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffea29474a1b4162aa4c75d596db3fbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":1783},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa43f1531d7044cbba23e68f083be512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":1783},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open News_page in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"news_page.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca8806f6cbdd4ae2b29b925011a4ef53",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
          "label":"menu_left",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":190,
              "height":1110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b03e7c1d90824fa4b47f032ddcb8faee",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"368263863e814b159c10c9d5a24d860a",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":190,
                      "height":1140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98da3ffdcaea4a50ae27f6649359b855",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":190,
                          "height":1140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"10a88ff6399d47a0a306c8db490bab2d",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":276},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbb190e58e334ac9ad61260d6706b60a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":276},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f0a126a01c1d482dae5fd764402ca89f",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":179},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"943efdde9c5245509a5c9455d2808b23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":179},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"c4d507d7efee4fb4b97c2dc0fe264016",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":133},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07065815eb7c481a9198dc30abe24862",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":133},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"50dfdb05d5404ba1ba69462a3992e594",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":320},
                    "size":{
                      "width":108,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9aa1275c0e7e4efa9cf675e3db8e3bd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":320},
                        "size":{
                          "width":108,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"205a90b14f2e4a57a6e515741bbee681",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":25},
                    "size":{
                      "width":163,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"610d2195b5d843649ba23e2b42077021",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":25},
                        "size":{
                          "width":163,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u28.png"}},
{
                  "id":"dab1689aff95418780f847a3615fc37e",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":228},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7544c56761924e5783fdf51ac1a9e0d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":228},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"77fc4f26ce0a473a86780fcb7885415c",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":122,
                      "y":315},
                    "size":{
                      "width":18,
                      "height":18},
                    "rotation":"270",
                    "textRotation":"270",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e651277358d64073b3b8825c728429eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":122,
                          "y":315},
                        "size":{
                          "width":18,
                          "height":18},
                        "rotation":"270",
                        "textRotation":"270",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u35.png"}},
{
                  "id":"5a7b62061b6e453c912393f1b2edd85b",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":127,
                      "y":316},
                    "size":{
                      "width":8,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88f5a2fcf7554d3a9ce34917aefbc1d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":127,
                          "y":316},
                        "size":{
                          "width":8,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f28420e224f3422d8839704a2778a1c5",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":512},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edf3b74e998249af860d21f1608bf397",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":512},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Vacancy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"vacancy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"455b6dcdf6e94b478b39261d2ebfbffe",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":471},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d16c76fa0df34826968b10cb0a3ad5d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":471},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Company in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"company.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"73f4a9c4994c4c81b30f78ebb004e85c",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":594},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"8f48d87c4e7e4c728bb02150bf96c8b5",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ef6bb60d58dc423f9d50f4bfba54c655",
                          "label":"",
                          "parentDynamicPanel":"73f4a9c4994c4c81b30f78ebb004e85c",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":139,
                              "height":63}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7023cc9c66394ca7b78d076679b49efc",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"73f4a9c4994c4c81b30f78ebb004e85c",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":139,
                                  "height":63}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/index/u31.png"}}]}]},
{
                  "id":"9ad1f8ec82814c86886155702d3fb282",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":429},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0199ba2ed124b01b3f5c0a887d84b79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":429},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Spravochnik in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"spravochnik.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"510488bdc09546fdb1c445b547f8f42a",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":388},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a9f115301a044e580a946b5fa5de465",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":388},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Calculator in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"calculator.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"c4f5d1f7691e464b86ffbe0796bd0488",
                  "label":"",
                  "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":553},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5b1ae0f55dc4d9d855c9240341be8d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd43ce6f0eeb49ae9973a4432bfd5ee4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":553},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Contacts_1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"contacts_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "2abfea0f6aa64532bbe2efb1cadd3e35":{
      "scriptId":"u0"},
    "138f1ecb3ac7402db622ce9fb9d5ead4":{
      "scriptId":"u1"},
    "e7c4c06223194097820c470594d2155c":{
      "scriptId":"u2"},
    "a42014ffd9544238a7c53e6287e40a66":{
      "scriptId":"u3"},
    "d3924cecbfab48c3817462c006268381":{
      "scriptId":"u4"},
    "da27a5ecf3ed474899284f7e85e085fb":{
      "scriptId":"u5"},
    "0f89ca70652e417ea6dc119709f85056":{
      "scriptId":"u6"},
    "ad6127ab708844a5b83c4d2ba3de1bc1":{
      "scriptId":"u7"},
    "2e251aebd42c459dba58cc4f00f6727f":{
      "scriptId":"u8"},
    "94ae4053419846d884cc29c0a312c318":{
      "scriptId":"u9"},
    "f240fef46e9945ca8c52545d11d931ca":{
      "scriptId":"u10"},
    "cb9bd2cedc79422fb48eb302d00cb58c":{
      "scriptId":"u11"},
    "86bfe3a0f5b640bc9ab3c88b9ef446f2":{
      "scriptId":"u12"},
    "969cf4d4996b43a9b9b70d5e14d754a1":{
      "scriptId":"u13"},
    "732072aa8b2547bab5d17b7d3d8ba3a1":{
      "scriptId":"u14"},
    "0d409aec104d47c1a74006f66de7f1ba":{
      "scriptId":"u15"},
    "e908bfa5861d414daf0104825d666a3a":{
      "scriptId":"u16"},
    "aa0d08809f1649c6afbae9d1e99f157a":{
      "scriptId":"u17"},
    "5515293a4ecc4c96a61dc3932535f778":{
      "scriptId":"u18"},
    "8c4184ea68a940a08c221e85cad1c558":{
      "scriptId":"u19"},
    "1c456392390649418dcac2f87f52a398":{
      "scriptId":"u20"},
    "25c75a6cfedc4ab3845719cc769cdcc6":{
      "scriptId":"u21"},
    "f82f6362344d4f299ba0b426596c6baf":{
      "scriptId":"u22"},
    "cb86fb1a9f54482a892958aa1d3619e6":{
      "scriptId":"u23"},
    "81802f99355c4e2ab9602f041db98ce4":{
      "scriptId":"u24"},
    "fb283f9b7e464292a8901d76f9bba1fb":{
      "scriptId":"u25"},
    "b2f8097a2f3b4a6288b9600b1e8d3bcf":{
      "scriptId":"u26"},
    "051160ac027d4340ab9479e54765d2db":{
      "scriptId":"u27"},
    "d7e9d31a608b443f8377171c6bbc935e":{
      "scriptId":"u28"},
    "ffea29474a1b4162aa4c75d596db3fbc":{
      "scriptId":"u29"},
    "aa43f1531d7044cbba23e68f083be512":{
      "scriptId":"u30"},
    "ca8806f6cbdd4ae2b29b925011a4ef53":{
      "scriptId":"u31",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u32"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u33"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u34"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u35"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u36"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u37"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u38"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u39"}},
    "dd43ce6f0eeb49ae9973a4432bfd5ee4":{
      "scriptId":"u40"},
    "368263863e814b159c10c9d5a24d860a":{
      "scriptId":"u41"},
    "98da3ffdcaea4a50ae27f6649359b855":{
      "scriptId":"u42"},
    "10a88ff6399d47a0a306c8db490bab2d":{
      "scriptId":"u43"},
    "fbb190e58e334ac9ad61260d6706b60a":{
      "scriptId":"u44"},
    "f0a126a01c1d482dae5fd764402ca89f":{
      "scriptId":"u45"},
    "943efdde9c5245509a5c9455d2808b23":{
      "scriptId":"u46"},
    "c4d507d7efee4fb4b97c2dc0fe264016":{
      "scriptId":"u47"},
    "07065815eb7c481a9198dc30abe24862":{
      "scriptId":"u48"},
    "50dfdb05d5404ba1ba69462a3992e594":{
      "scriptId":"u49"},
    "9aa1275c0e7e4efa9cf675e3db8e3bd8":{
      "scriptId":"u50"},
    "205a90b14f2e4a57a6e515741bbee681":{
      "scriptId":"u51"},
    "610d2195b5d843649ba23e2b42077021":{
      "scriptId":"u52"},
    "dab1689aff95418780f847a3615fc37e":{
      "scriptId":"u53"},
    "7544c56761924e5783fdf51ac1a9e0d8":{
      "scriptId":"u54"},
    "77fc4f26ce0a473a86780fcb7885415c":{
      "scriptId":"u55"},
    "e651277358d64073b3b8825c728429eb":{
      "scriptId":"u56"},
    "5a7b62061b6e453c912393f1b2edd85b":{
      "scriptId":"u57"},
    "88f5a2fcf7554d3a9ce34917aefbc1d7":{
      "scriptId":"u58"},
    "f28420e224f3422d8839704a2778a1c5":{
      "scriptId":"u59"},
    "edf3b74e998249af860d21f1608bf397":{
      "scriptId":"u60"},
    "455b6dcdf6e94b478b39261d2ebfbffe":{
      "scriptId":"u61"},
    "d16c76fa0df34826968b10cb0a3ad5d3":{
      "scriptId":"u62"},
    "73f4a9c4994c4c81b30f78ebb004e85c":{
      "scriptId":"u63"},
    "ef6bb60d58dc423f9d50f4bfba54c655":{
      "scriptId":"u64"},
    "7023cc9c66394ca7b78d076679b49efc":{
      "scriptId":"u65"},
    "9ad1f8ec82814c86886155702d3fb282":{
      "scriptId":"u66"},
    "d0199ba2ed124b01b3f5c0a887d84b79":{
      "scriptId":"u67"},
    "510488bdc09546fdb1c445b547f8f42a":{
      "scriptId":"u68"},
    "4a9f115301a044e580a946b5fa5de465":{
      "scriptId":"u69"},
    "c4f5d1f7691e464b86ffbe0796bd0488":{
      "scriptId":"u70"},
    "c5b1ae0f55dc4d9d855c9240341be8d4":{
      "scriptId":"u71"}}});