$axure.loadCurrentPage({
  "url":"spravochnik.html",
  "generationDate":new Date(1399457452678.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0221a91b12574321a565299363fdddc4",
    "type":"Axure:Page",
    "name":"Spravochnik",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b4d42c1919384deda692986dbe72c189",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":83},
            "size":{
              "width":256,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e07091a9065457fad9b8efb8582aee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":83},
                "size":{
                  "width":256,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10abbf1a11714c2abeced0e8acaa6766",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"0e650664de8648ef8a2a113b40f4eb1d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"dc81003c92a54538bf60fb37784eb46b"},
{
          "id":"b8c60a3d97b54bd69de620588d57f58a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":230,
              "y":280},
            "size":{
              "width":721,
              "height":145}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de8b9b7b63cf436f8588f79bd5cadd2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":230,
                  "y":280},
                "size":{
                  "width":721,
                  "height":145}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9af294a335394ce8a92661935388873a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":182},
            "size":{
              "width":707,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d544136d7004fce99e5ef803f43c57f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":182},
                "size":{
                  "width":707,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ee8baf7f3424e27acac3b50e4f1f8a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":229,
              "y":1289},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f3f26b37c64fb793e5bafbd62c021b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":229,
                  "y":1289},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u51.png"}},
{
          "id":"fdc118e9b4ac47d9b61986647f497c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":1003},
            "size":{
              "width":141,
              "height":141},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53db2f696a504a22a913bc578b8a0b78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":1003},
                "size":{
                  "width":141,
                  "height":141},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/spravochnik/u51.png"}},
{
          "id":"642e062693fc4385b6c3d6273833ad97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":1015},
            "size":{
              "width":180,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"437afe1266fc4d4c93182c32214536c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":391,
                  "y":1015},
                "size":{
                  "width":180,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcd819cbc8f44a18843a0819cf376ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":610,
              "y":1003},
            "size":{
              "width":141,
              "height":141},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"706866424e5b4f5a99e06c8133f48067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":610,
                  "y":1003},
                "size":{
                  "width":141,
                  "height":141},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/spravochnik/u51.png"}},
{
          "id":"6f76a8a35d5d45ad8bf0b075cf28250f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":769,
              "y":1015},
            "size":{
              "width":180,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f6ff7f5a0484398a426496367f0aa33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":769,
                  "y":1015},
                "size":{
                  "width":180,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"defea13cda6949c7a7567889c24dab2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":393,
              "y":2050},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35288b927d8244c9b4ed26a156faee5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":393,
                  "y":2050},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/spravochnik/u59.png"}},
{
          "id":"93ff8ab10ffb44c3a877a5f154e82201",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":513,
              "y":2068},
            "size":{
              "width":370,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd05e511e50c420b825b6e48748744fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":513,
                  "y":2068},
                "size":{
                  "width":370,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1037af20e7064e72846cb0e8f6cd4909",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":2160},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8464971edad4b0ebeca09dce6cf73d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":2160},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u67.png"}},
{
          "id":"8fa050da780745988a9c9eb47c500e5a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":451},
            "size":{
              "width":730,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d108810e9a7743539ba2de4ea915c853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":451},
                "size":{
                  "width":730,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u4.png"}},
{
          "id":"27717e63815d46e0a17fc704ec5c8e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":229,
              "y":1200},
            "size":{
              "width":721,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709e48ccb1484d04930f75b38a5dd193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":229,
                  "y":1200},
                "size":{
                  "width":721,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1fd6d5aeb9c4c18ae66e824d801a1c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":933},
            "size":{
              "width":438,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63d88eb1c605443bab84d520a2929a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":933},
                "size":{
                  "width":438,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"795ec97a84084c8caa02cb199afda05b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":1480},
            "size":{
              "width":720,
              "height":511},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c01a8432730a4e859d09369ff0a423cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":1480},
                "size":{
                  "width":720,
                  "height":511},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/spravochnik/u71.png"}},
{
          "id":"b49855430553481c9689a9113c9ee6a5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":252,
              "y":1533},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"86dd7b36e7664a69907f7dd6d88a6eb3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":252,
              "y":1620},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"d95c8a9004694a39ba271a16fc2fc9b7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":575,
              "y":1620},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"9b5f4f46ca224601bfd3129593ae6b29",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":575,
              "y":1533},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"6e803947298141b38a687ee7e8e8ea23",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":1704},
            "size":{
              "width":599,
              "height":161}},
          "adaptiveStyles":{
}},
{
          "id":"88e5d07eae564d4fb56c63c8742c5733",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":255,
              "y":1723},
            "size":{
              "width":574,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37cc537776d84e568698d6a37bb76beb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":255,
                  "y":1723},
                "size":{
                  "width":574,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ee83dfb047b4d039223ea04a78d9c75",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":1895},
            "size":{
              "width":141,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"5afc5a8f620d4375b7fb98fe20716bd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1403},
            "size":{
              "width":342,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbbb52391a9240ab8610b1b327d9e4c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1403},
                "size":{
                  "width":342,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}},
    "dc81003c92a54538bf60fb37784eb46b":{
      "packageId":"dc81003c92a54538bf60fb37784eb46b",
      "type":"Axure:Master",
      "name":"menu2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"530a529d390b4c9a838ce9c72ad17787",
            "label":"menu2",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Index in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"index.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"44360c788e1f406d8047349492cb8c21",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"619ddf7225a24c80a1fe2edf473be62d",
                    "label":"menu_2_linker",
                    "parentDynamicPanel":"530a529d390b4c9a838ce9c72ad17787",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":190,
                        "height":1110}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Index in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"index.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "fixedHorizontal":"left",
                    "fixedMarginHorizontal":0,
                    "fixedVertical":"top",
                    "fixedMarginVertical":0,
                    "fixedKeepInFront":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"c88ca855f21840e0b23cf0212d2f5960",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"3a535a13d05b4cd3b8bb653c7cd28a40",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2},
                              "size":{
                                "width":190,
                                "height":1140},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"815d4fcb78194cb2a66e6615f66e21ac",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fill":{
                                    "fillType":"solid",
                                    "color":0xFFF2F2F2},
                                  "size":{
                                    "width":190,
                                    "height":1140},
                                  "borderFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFF}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Index in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"index.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"images/index/u14.png"}},
{
                            "id":"2cebbca325b84901bc00b8facc53d9a4",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":276},
                              "size":{
                                "width":92,
                                "height":29}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"c88ea0c642ac47f8af22fb96dc904f04",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":276},
                                  "size":{
                                    "width":92,
                                    "height":29}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"94bd8067af9e4de3a72d52cebc09e6c5",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":179},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"1eb5a40ae6e94420aaf0b9e57fe0d3cf",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":179},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"95772666754c44519044348582528cb5",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":133},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b9e297617d3d47ffb197893d4eb51790",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":133},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"d726c37838c0440089becb9d86d0cb59",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":320},
                              "size":{
                                "width":108,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"275e9603470541489cc27d4f90924ff4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":320},
                                  "size":{
                                    "width":108,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"70241218c87940a6a628f5b99ae69608",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"imageBox",
                            "styleType":"imageBox",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":11,
                                "y":25},
                              "size":{
                                "width":163,
                                "height":75}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"a7dbf897779c421898e93a7ed5a3b3e6",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "location":{
                                    "x":11,
                                    "y":25},
                                  "size":{
                                    "width":163,
                                    "height":75}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/index/u28.png"}},
{
                            "id":"4575fcaa70374d909c39524adf0e8716",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":228},
                              "size":{
                                "width":92,
                                "height":29}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"8755bf0be9d742b18f36260df98f3ddd",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":228},
                                  "size":{
                                    "width":92,
                                    "height":29}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"196af03019284c6daa870061f8f84285",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF999999},
                              "location":{
                                "x":122,
                                "y":315},
                              "size":{
                                "width":18,
                                "height":18},
                              "rotation":"270",
                              "textRotation":"270",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"8c203a3a790448168c47491fe67b6282",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fill":{
                                    "fillType":"solid",
                                    "color":0xFF999999},
                                  "location":{
                                    "x":122,
                                    "y":315},
                                  "size":{
                                    "width":18,
                                    "height":18},
                                  "rotation":"270",
                                  "textRotation":"270",
                                  "borderFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFF}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/index/u35.png"}},
{
                            "id":"a319345e7f9c48c0a7c660c1f175073a",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":127,
                                "y":316},
                              "size":{
                                "width":8,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b33e28b35e4a41d1982f6459b5b3d311",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":127,
                                    "y":316},
                                  "size":{
                                    "width":8,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"09cb2665d7994abea54979ed6380d811",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":512},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6c263e9b80144315b51506c007e0c25a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":512},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"93500876446241f29f2ceddccfbaeda7",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":471},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b5c3dc614bdb435c88d36deefb2f7bc8",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":471},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"84f36592f9bc407dab1106f08a70655a",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"dynamicPanel",
                            "styleType":"dynamicPanel",
                            "disabled":true,
                            "visible":true,
                            "style":{
                              "location":{
                                "x":19,
                                "y":594},
                              "size":{
                                "width":10,
                                "height":10}},
                            "adaptiveStyles":{
},
                            "scrollbars":"none",
                            "fitToContent":true,
                            "propagate":false,
                            "diagrams":[{
                                "id":"c07f7c7d8b4e4f36bf2a382a2114a4a1",
                                "label":"State1",
                                "type":"Axure:PanelDiagram",
                                "objects":[{
                                    "id":"b5c93bec40d243fcb0902e1e56599910",
                                    "label":"",
                                    "parentDynamicPanel":"84f36592f9bc407dab1106f08a70655a",
                                    "type":"imageBox",
                                    "styleType":"imageBox",
                                    "visible":true,
                                    "style":{
                                      "size":{
                                        "width":139,
                                        "height":63}},
                                    "adaptiveStyles":{
},
                                    "objects":[{
                                        "id":"52c1c8968a3c484998761a755e9cabb2",
                                        "label":"",
                                        "isContained":true,
                                        "parentDynamicPanel":"84f36592f9bc407dab1106f08a70655a",
                                        "type":"richTextPanel",
                                        "styleType":"paragraph",
                                        "visible":true,
                                        "style":{
                                          "size":{
                                            "width":139,
                                            "height":63}},
                                        "adaptiveStyles":{
}}],
                                    "images":{
                                      "normal~":"images/index/u31.png"}}]}]},
{
                            "id":"95326c3777ee42ce8d38d01b5cc9f498",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":51,
                                "y":429},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"30cb2d0b59ce48109fbe487c07b390b3",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":51,
                                    "y":429},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"f500f38d86014c0188e8e5de6eb93757",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":51,
                                "y":388},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"a7c452fd78cb4968b8af4357aa5e2626",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":51,
                                    "y":388},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"3e51f3fb4fdb49c1ac4d4c42fe62ba0d",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":553},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"e52a6e52f3ce4db1a1eb472f341dd70a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":553},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "b4d42c1919384deda692986dbe72c189":{
      "scriptId":"u0"},
    "4e07091a9065457fad9b8efb8582aee0":{
      "scriptId":"u1"},
    "10abbf1a11714c2abeced0e8acaa6766":{
      "scriptId":"u2",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u3"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u4"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u5"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u6"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u7"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u8"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u9"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u10"}},
    "0e650664de8648ef8a2a113b40f4eb1d":{
      "scriptId":"u11",
      "530a529d390b4c9a838ce9c72ad17787":{
        "scriptId":"u12"},
      "619ddf7225a24c80a1fe2edf473be62d":{
        "scriptId":"u13"},
      "3a535a13d05b4cd3b8bb653c7cd28a40":{
        "scriptId":"u14"},
      "815d4fcb78194cb2a66e6615f66e21ac":{
        "scriptId":"u15"},
      "2cebbca325b84901bc00b8facc53d9a4":{
        "scriptId":"u16"},
      "c88ea0c642ac47f8af22fb96dc904f04":{
        "scriptId":"u17"},
      "94bd8067af9e4de3a72d52cebc09e6c5":{
        "scriptId":"u18"},
      "1eb5a40ae6e94420aaf0b9e57fe0d3cf":{
        "scriptId":"u19"},
      "95772666754c44519044348582528cb5":{
        "scriptId":"u20"},
      "b9e297617d3d47ffb197893d4eb51790":{
        "scriptId":"u21"},
      "d726c37838c0440089becb9d86d0cb59":{
        "scriptId":"u22"},
      "275e9603470541489cc27d4f90924ff4":{
        "scriptId":"u23"},
      "70241218c87940a6a628f5b99ae69608":{
        "scriptId":"u24"},
      "a7dbf897779c421898e93a7ed5a3b3e6":{
        "scriptId":"u25"},
      "4575fcaa70374d909c39524adf0e8716":{
        "scriptId":"u26"},
      "8755bf0be9d742b18f36260df98f3ddd":{
        "scriptId":"u27"},
      "196af03019284c6daa870061f8f84285":{
        "scriptId":"u28"},
      "8c203a3a790448168c47491fe67b6282":{
        "scriptId":"u29"},
      "a319345e7f9c48c0a7c660c1f175073a":{
        "scriptId":"u30"},
      "b33e28b35e4a41d1982f6459b5b3d311":{
        "scriptId":"u31"},
      "09cb2665d7994abea54979ed6380d811":{
        "scriptId":"u32"},
      "6c263e9b80144315b51506c007e0c25a":{
        "scriptId":"u33"},
      "93500876446241f29f2ceddccfbaeda7":{
        "scriptId":"u34"},
      "b5c3dc614bdb435c88d36deefb2f7bc8":{
        "scriptId":"u35"},
      "84f36592f9bc407dab1106f08a70655a":{
        "scriptId":"u36"},
      "b5c93bec40d243fcb0902e1e56599910":{
        "scriptId":"u37"},
      "52c1c8968a3c484998761a755e9cabb2":{
        "scriptId":"u38"},
      "95326c3777ee42ce8d38d01b5cc9f498":{
        "scriptId":"u39"},
      "30cb2d0b59ce48109fbe487c07b390b3":{
        "scriptId":"u40"},
      "f500f38d86014c0188e8e5de6eb93757":{
        "scriptId":"u41"},
      "a7c452fd78cb4968b8af4357aa5e2626":{
        "scriptId":"u42"},
      "3e51f3fb4fdb49c1ac4d4c42fe62ba0d":{
        "scriptId":"u43"},
      "e52a6e52f3ce4db1a1eb472f341dd70a":{
        "scriptId":"u44"}},
    "b8c60a3d97b54bd69de620588d57f58a":{
      "scriptId":"u45"},
    "de8b9b7b63cf436f8588f79bd5cadd2e":{
      "scriptId":"u46"},
    "9af294a335394ce8a92661935388873a":{
      "scriptId":"u47"},
    "7d544136d7004fce99e5ef803f43c57f":{
      "scriptId":"u48"},
    "8ee8baf7f3424e27acac3b50e4f1f8a5":{
      "scriptId":"u49"},
    "23f3f26b37c64fb793e5bafbd62c021b":{
      "scriptId":"u50"},
    "fdc118e9b4ac47d9b61986647f497c73":{
      "scriptId":"u51"},
    "53db2f696a504a22a913bc578b8a0b78":{
      "scriptId":"u52"},
    "642e062693fc4385b6c3d6273833ad97":{
      "scriptId":"u53"},
    "437afe1266fc4d4c93182c32214536c7":{
      "scriptId":"u54"},
    "bcd819cbc8f44a18843a0819cf376ac8":{
      "scriptId":"u55"},
    "706866424e5b4f5a99e06c8133f48067":{
      "scriptId":"u56"},
    "6f76a8a35d5d45ad8bf0b075cf28250f":{
      "scriptId":"u57"},
    "8f6ff7f5a0484398a426496367f0aa33":{
      "scriptId":"u58"},
    "defea13cda6949c7a7567889c24dab2e":{
      "scriptId":"u59"},
    "35288b927d8244c9b4ed26a156faee5b":{
      "scriptId":"u60"},
    "93ff8ab10ffb44c3a877a5f154e82201":{
      "scriptId":"u61"},
    "dd05e511e50c420b825b6e48748744fb":{
      "scriptId":"u62"},
    "1037af20e7064e72846cb0e8f6cd4909":{
      "scriptId":"u63"},
    "b8464971edad4b0ebeca09dce6cf73d2":{
      "scriptId":"u64"},
    "8fa050da780745988a9c9eb47c500e5a":{
      "scriptId":"u65"},
    "d108810e9a7743539ba2de4ea915c853":{
      "scriptId":"u66"},
    "27717e63815d46e0a17fc704ec5c8e84":{
      "scriptId":"u67"},
    "709e48ccb1484d04930f75b38a5dd193":{
      "scriptId":"u68"},
    "b1fd6d5aeb9c4c18ae66e824d801a1c1":{
      "scriptId":"u69"},
    "63d88eb1c605443bab84d520a2929a73":{
      "scriptId":"u70"},
    "795ec97a84084c8caa02cb199afda05b":{
      "scriptId":"u71"},
    "c01a8432730a4e859d09369ff0a423cb":{
      "scriptId":"u72"},
    "b49855430553481c9689a9113c9ee6a5":{
      "scriptId":"u73"},
    "86dd7b36e7664a69907f7dd6d88a6eb3":{
      "scriptId":"u74"},
    "d95c8a9004694a39ba271a16fc2fc9b7":{
      "scriptId":"u75"},
    "9b5f4f46ca224601bfd3129593ae6b29":{
      "scriptId":"u76"},
    "6e803947298141b38a687ee7e8e8ea23":{
      "scriptId":"u77"},
    "88e5d07eae564d4fb56c63c8742c5733":{
      "scriptId":"u78"},
    "37cc537776d84e568698d6a37bb76beb":{
      "scriptId":"u79"},
    "1ee83dfb047b4d039223ea04a78d9c75":{
      "scriptId":"u80"},
    "5afc5a8f620d4375b7fb98fe20716bd0":{
      "scriptId":"u81"},
    "cbbb52391a9240ab8610b1b327d9e4c3":{
      "scriptId":"u82"}}});