$axure.loadCurrentPage({
  "url":"calculator.html",
  "generationDate":new Date(1399457452304.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1dffa2db6b1148359fddecf7283f9964",
    "type":"Axure:Page",
    "name":"Calculator",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e06cbc6eead486b8c31ff72f2acbd59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":230,
              "y":983},
            "size":{
              "width":190,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce57c04dfc9446308a0f55fcc4e200a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":230,
                  "y":983},
                "size":{
                  "width":190,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d42c1919384deda692986dbe72c189",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":83},
            "size":{
              "width":602,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e07091a9065457fad9b8efb8582aee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":83},
                "size":{
                  "width":602,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcb0e9c4cbd440dfb93fcf6984702cf6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230.000030517578,
              "y":280.000030517578},
            "size":{
              "width":730,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe90675009d47c0adbeebb8ce94d168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230.000030517578,
                  "y":280.000030517578},
                "size":{
                  "width":730,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u4.png"}},
{
          "id":"10abbf1a11714c2abeced0e8acaa6766",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"0e650664de8648ef8a2a113b40f4eb1d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"dc81003c92a54538bf60fb37784eb46b"},
{
          "id":"cb922276d58c45518985b2b59a044b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":847},
            "size":{
              "width":116,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a3205707fed4551aeec9dff4aa46523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":847},
                "size":{
                  "width":116,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u49.png"}},
{
          "id":"8456c750fa9d4161a35cba11bbae6754",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":560,
              "y":590},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18a703a6d3c249e6893b4eefb129ce54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":560,
                  "y":590},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u51.png"}},
{
          "id":"1b3af99067e44af4b875d0496b0ec348",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":730,
              "y":590},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ada0749c164991a4b62f75b0e40f0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":730,
                  "y":590},
                "size":{
                  "width":140,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u51.png"}},
{
          "id":"9af294a335394ce8a92661935388873a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":231,
              "y":1044},
            "size":{
              "width":227,
              "height":169}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d544136d7004fce99e5ef803f43c57f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":231,
                  "y":1044},
                "size":{
                  "width":227,
                  "height":169}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21bcfae227714da981a555a22f0bab59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":469,
              "y":983},
            "size":{
              "width":190,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09c7a20cf0ac42f7bf8e403041822c78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":469,
                  "y":983},
                "size":{
                  "width":190,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e32a26a1777542f1a76644be9977baa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":472,
              "y":847},
            "size":{
              "width":116,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7d131fdc9a42aab4077dcd483b82e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":472,
                  "y":847},
                "size":{
                  "width":116,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u49.png"}},
{
          "id":"4b4dab0b826449118d593d933bfa033a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":470,
              "y":1043},
            "size":{
              "width":227,
              "height":169}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cea203e2d33840659e2fdfaa828e01c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":470,
                  "y":1043},
                "size":{
                  "width":227,
                  "height":169}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a32369c96e4f47a0816c1032828395d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":709,
              "y":983},
            "size":{
              "width":190,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"166a2b908530496795fb35afcb9cee6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":709,
                  "y":983},
                "size":{
                  "width":190,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b82c732438954509b13a155212f569f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":707,
              "y":847},
            "size":{
              "width":116,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db36e83c99ae4ce7af1f9f92c32175ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":707,
                  "y":847},
                "size":{
                  "width":116,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u49.png"}},
{
          "id":"81961c3ce3b24796b3226ed1856412e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":710,
              "y":1031},
            "size":{
              "width":227,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca7750d6c78344c1a44e0720fe2a8ce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":710,
                  "y":1031},
                "size":{
                  "width":227,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ceb880178f6847b2b8b1ea397c4566f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1910},
            "size":{
              "width":290,
              "height":140},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2687bc01e88b4d9dbee2842b6f5cf7e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1910},
                "size":{
                  "width":290,
                  "height":140},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u69.png"}},
{
          "id":"39c96ef3b0034d54a51d9a51809602a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":1260},
            "size":{
              "width":240,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b128cd9fd3ce4e069e693800426ef136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":1260},
                "size":{
                  "width":240,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u71.png"}},
{
          "id":"a8eabf7e20c847a89369ea918ef2c7af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":469,
              "y":1260},
            "size":{
              "width":240,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"330a7ba2ab6248c4ad540f90bcaa341c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":469,
                  "y":1260},
                "size":{
                  "width":240,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u73.png"}},
{
          "id":"eb416d8126b4464d92cbfac9105fd049",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":708,
              "y":1260},
            "size":{
              "width":243,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b658e46706de4f399f4b00389f82f642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":708,
                  "y":1260},
                "size":{
                  "width":243,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/calculator/u75.png"}},
{
          "id":"7e76c872ed6841f5aaddaabcf99c02b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "location":{
              "x":230,
              "y":180},
            "size":{
              "width":680,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1024700067c445588923ac6c2edec6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "location":{
                  "x":230,
                  "y":180},
                "size":{
                  "width":680,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c20fd73c576e48638d3ae15ded17ae2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":758},
            "size":{
              "width":382,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c98eab81a7f4b319aad35d0c0cb4225",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":758},
                "size":{
                  "width":382,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}},
    "dc81003c92a54538bf60fb37784eb46b":{
      "packageId":"dc81003c92a54538bf60fb37784eb46b",
      "type":"Axure:Master",
      "name":"menu2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"530a529d390b4c9a838ce9c72ad17787",
            "label":"menu2",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Index in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"index.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"44360c788e1f406d8047349492cb8c21",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"619ddf7225a24c80a1fe2edf473be62d",
                    "label":"menu_2_linker",
                    "parentDynamicPanel":"530a529d390b4c9a838ce9c72ad17787",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":190,
                        "height":1110}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Index in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"index.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "fixedHorizontal":"left",
                    "fixedMarginHorizontal":0,
                    "fixedVertical":"top",
                    "fixedMarginVertical":0,
                    "fixedKeepInFront":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"c88ca855f21840e0b23cf0212d2f5960",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"3a535a13d05b4cd3b8bb653c7cd28a40",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFF2F2F2},
                              "size":{
                                "width":190,
                                "height":1140},
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"815d4fcb78194cb2a66e6615f66e21ac",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fill":{
                                    "fillType":"solid",
                                    "color":0xFFF2F2F2},
                                  "size":{
                                    "width":190,
                                    "height":1140},
                                  "borderFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFF}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Index in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"index.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"images/index/u14.png"}},
{
                            "id":"2cebbca325b84901bc00b8facc53d9a4",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":276},
                              "size":{
                                "width":92,
                                "height":29}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"c88ea0c642ac47f8af22fb96dc904f04",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":276},
                                  "size":{
                                    "width":92,
                                    "height":29}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"94bd8067af9e4de3a72d52cebc09e6c5",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":179},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"1eb5a40ae6e94420aaf0b9e57fe0d3cf",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":179},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"95772666754c44519044348582528cb5",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":133},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b9e297617d3d47ffb197893d4eb51790",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":133},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"d726c37838c0440089becb9d86d0cb59",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":320},
                              "size":{
                                "width":108,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"275e9603470541489cc27d4f90924ff4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":320},
                                  "size":{
                                    "width":108,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"70241218c87940a6a628f5b99ae69608",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"imageBox",
                            "styleType":"imageBox",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":11,
                                "y":25},
                              "size":{
                                "width":163,
                                "height":75}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"a7dbf897779c421898e93a7ed5a3b3e6",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "location":{
                                    "x":11,
                                    "y":25},
                                  "size":{
                                    "width":163,
                                    "height":75}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/index/u28.png"}},
{
                            "id":"4575fcaa70374d909c39524adf0e8716",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Bold', 'Arial'",
                              "fontSize":"16px",
                              "fontWeight":"700",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":228},
                              "size":{
                                "width":92,
                                "height":29}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"8755bf0be9d742b18f36260df98f3ddd",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Bold', 'Arial'",
                                  "fontSize":"16px",
                                  "fontWeight":"700",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":228},
                                  "size":{
                                    "width":92,
                                    "height":29}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"scrollToWidget",
                                        "description":"Scroll to Widget"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"196af03019284c6daa870061f8f84285",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"buttonShape",
                            "visible":true,
                            "style":{
                              "fill":{
                                "fillType":"solid",
                                "color":0xFF999999},
                              "location":{
                                "x":122,
                                "y":315},
                              "size":{
                                "width":18,
                                "height":18},
                              "rotation":"270",
                              "textRotation":"270",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFFFF}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"8c203a3a790448168c47491fe67b6282",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fill":{
                                    "fillType":"solid",
                                    "color":0xFF999999},
                                  "location":{
                                    "x":122,
                                    "y":315},
                                  "size":{
                                    "width":18,
                                    "height":18},
                                  "rotation":"270",
                                  "textRotation":"270",
                                  "borderFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFF}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/index/u35.png"}},
{
                            "id":"a319345e7f9c48c0a7c660c1f175073a",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":127,
                                "y":316},
                              "size":{
                                "width":8,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b33e28b35e4a41d1982f6459b5b3d311",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":127,
                                    "y":316},
                                  "size":{
                                    "width":8,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"09cb2665d7994abea54979ed6380d811",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":512},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6c263e9b80144315b51506c007e0c25a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":512},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"93500876446241f29f2ceddccfbaeda7",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":471},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"b5c3dc614bdb435c88d36deefb2f7bc8",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":471},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"84f36592f9bc407dab1106f08a70655a",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"dynamicPanel",
                            "styleType":"dynamicPanel",
                            "disabled":true,
                            "visible":true,
                            "style":{
                              "location":{
                                "x":19,
                                "y":594},
                              "size":{
                                "width":10,
                                "height":10}},
                            "adaptiveStyles":{
},
                            "scrollbars":"none",
                            "fitToContent":true,
                            "propagate":false,
                            "diagrams":[{
                                "id":"c07f7c7d8b4e4f36bf2a382a2114a4a1",
                                "label":"State1",
                                "type":"Axure:PanelDiagram",
                                "objects":[{
                                    "id":"b5c93bec40d243fcb0902e1e56599910",
                                    "label":"",
                                    "parentDynamicPanel":"84f36592f9bc407dab1106f08a70655a",
                                    "type":"imageBox",
                                    "styleType":"imageBox",
                                    "visible":true,
                                    "style":{
                                      "size":{
                                        "width":139,
                                        "height":63}},
                                    "adaptiveStyles":{
},
                                    "objects":[{
                                        "id":"52c1c8968a3c484998761a755e9cabb2",
                                        "label":"",
                                        "isContained":true,
                                        "parentDynamicPanel":"84f36592f9bc407dab1106f08a70655a",
                                        "type":"richTextPanel",
                                        "styleType":"paragraph",
                                        "visible":true,
                                        "style":{
                                          "size":{
                                            "width":139,
                                            "height":63}},
                                        "adaptiveStyles":{
}}],
                                    "images":{
                                      "normal~":"images/index/u31.png"}}]}]},
{
                            "id":"95326c3777ee42ce8d38d01b5cc9f498",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":51,
                                "y":429},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"30cb2d0b59ce48109fbe487c07b390b3",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":51,
                                    "y":429},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"f500f38d86014c0188e8e5de6eb93757",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":51,
                                "y":388},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"a7c452fd78cb4968b8af4357aa5e2626",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":51,
                                    "y":388},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"3e51f3fb4fdb49c1ac4d4c42fe62ba0d",
                            "label":"",
                            "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "stateStyles":{
                                "mouseOver":{
                                  "underline":true},
                                "selected":{
                                  "underline":true}},
                              "location":{
                                "x":50,
                                "y":553},
                              "size":{
                                "width":90,
                                "height":28}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"e52a6e52f3ce4db1a1eb472f341dd70a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"619ddf7225a24c80a1fe2edf473be62d",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "stateStyles":{
                                    "mouseOver":{
                                      "underline":true},
                                    "selected":{
                                      "underline":true}},
                                  "location":{
                                    "x":50,
                                    "y":553},
                                  "size":{
                                    "width":90,
                                    "height":28}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "selected~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "1e06cbc6eead486b8c31ff72f2acbd59":{
      "scriptId":"u0"},
    "ce57c04dfc9446308a0f55fcc4e200a1":{
      "scriptId":"u1"},
    "b4d42c1919384deda692986dbe72c189":{
      "scriptId":"u2"},
    "4e07091a9065457fad9b8efb8582aee0":{
      "scriptId":"u3"},
    "fcb0e9c4cbd440dfb93fcf6984702cf6":{
      "scriptId":"u4"},
    "6fe90675009d47c0adbeebb8ce94d168":{
      "scriptId":"u5"},
    "10abbf1a11714c2abeced0e8acaa6766":{
      "scriptId":"u6",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u7"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u8"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u9"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u10"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u11"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u12"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u13"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u14"}},
    "0e650664de8648ef8a2a113b40f4eb1d":{
      "scriptId":"u15",
      "530a529d390b4c9a838ce9c72ad17787":{
        "scriptId":"u16"},
      "619ddf7225a24c80a1fe2edf473be62d":{
        "scriptId":"u17"},
      "3a535a13d05b4cd3b8bb653c7cd28a40":{
        "scriptId":"u18"},
      "815d4fcb78194cb2a66e6615f66e21ac":{
        "scriptId":"u19"},
      "2cebbca325b84901bc00b8facc53d9a4":{
        "scriptId":"u20"},
      "c88ea0c642ac47f8af22fb96dc904f04":{
        "scriptId":"u21"},
      "94bd8067af9e4de3a72d52cebc09e6c5":{
        "scriptId":"u22"},
      "1eb5a40ae6e94420aaf0b9e57fe0d3cf":{
        "scriptId":"u23"},
      "95772666754c44519044348582528cb5":{
        "scriptId":"u24"},
      "b9e297617d3d47ffb197893d4eb51790":{
        "scriptId":"u25"},
      "d726c37838c0440089becb9d86d0cb59":{
        "scriptId":"u26"},
      "275e9603470541489cc27d4f90924ff4":{
        "scriptId":"u27"},
      "70241218c87940a6a628f5b99ae69608":{
        "scriptId":"u28"},
      "a7dbf897779c421898e93a7ed5a3b3e6":{
        "scriptId":"u29"},
      "4575fcaa70374d909c39524adf0e8716":{
        "scriptId":"u30"},
      "8755bf0be9d742b18f36260df98f3ddd":{
        "scriptId":"u31"},
      "196af03019284c6daa870061f8f84285":{
        "scriptId":"u32"},
      "8c203a3a790448168c47491fe67b6282":{
        "scriptId":"u33"},
      "a319345e7f9c48c0a7c660c1f175073a":{
        "scriptId":"u34"},
      "b33e28b35e4a41d1982f6459b5b3d311":{
        "scriptId":"u35"},
      "09cb2665d7994abea54979ed6380d811":{
        "scriptId":"u36"},
      "6c263e9b80144315b51506c007e0c25a":{
        "scriptId":"u37"},
      "93500876446241f29f2ceddccfbaeda7":{
        "scriptId":"u38"},
      "b5c3dc614bdb435c88d36deefb2f7bc8":{
        "scriptId":"u39"},
      "84f36592f9bc407dab1106f08a70655a":{
        "scriptId":"u40"},
      "b5c93bec40d243fcb0902e1e56599910":{
        "scriptId":"u41"},
      "52c1c8968a3c484998761a755e9cabb2":{
        "scriptId":"u42"},
      "95326c3777ee42ce8d38d01b5cc9f498":{
        "scriptId":"u43"},
      "30cb2d0b59ce48109fbe487c07b390b3":{
        "scriptId":"u44"},
      "f500f38d86014c0188e8e5de6eb93757":{
        "scriptId":"u45"},
      "a7c452fd78cb4968b8af4357aa5e2626":{
        "scriptId":"u46"},
      "3e51f3fb4fdb49c1ac4d4c42fe62ba0d":{
        "scriptId":"u47"},
      "e52a6e52f3ce4db1a1eb472f341dd70a":{
        "scriptId":"u48"}},
    "cb922276d58c45518985b2b59a044b04":{
      "scriptId":"u49"},
    "8a3205707fed4551aeec9dff4aa46523":{
      "scriptId":"u50"},
    "8456c750fa9d4161a35cba11bbae6754":{
      "scriptId":"u51"},
    "18a703a6d3c249e6893b4eefb129ce54":{
      "scriptId":"u52"},
    "1b3af99067e44af4b875d0496b0ec348":{
      "scriptId":"u53"},
    "09ada0749c164991a4b62f75b0e40f0a":{
      "scriptId":"u54"},
    "9af294a335394ce8a92661935388873a":{
      "scriptId":"u55"},
    "7d544136d7004fce99e5ef803f43c57f":{
      "scriptId":"u56"},
    "21bcfae227714da981a555a22f0bab59":{
      "scriptId":"u57"},
    "09c7a20cf0ac42f7bf8e403041822c78":{
      "scriptId":"u58"},
    "e32a26a1777542f1a76644be9977baa9":{
      "scriptId":"u59"},
    "8e7d131fdc9a42aab4077dcd483b82e0":{
      "scriptId":"u60"},
    "4b4dab0b826449118d593d933bfa033a":{
      "scriptId":"u61"},
    "cea203e2d33840659e2fdfaa828e01c1":{
      "scriptId":"u62"},
    "a32369c96e4f47a0816c1032828395d8":{
      "scriptId":"u63"},
    "166a2b908530496795fb35afcb9cee6f":{
      "scriptId":"u64"},
    "b82c732438954509b13a155212f569f7":{
      "scriptId":"u65"},
    "db36e83c99ae4ce7af1f9f92c32175ca":{
      "scriptId":"u66"},
    "81961c3ce3b24796b3226ed1856412e0":{
      "scriptId":"u67"},
    "ca7750d6c78344c1a44e0720fe2a8ce1":{
      "scriptId":"u68"},
    "ceb880178f6847b2b8b1ea397c4566f2":{
      "scriptId":"u69"},
    "2687bc01e88b4d9dbee2842b6f5cf7e3":{
      "scriptId":"u70"},
    "39c96ef3b0034d54a51d9a51809602a2":{
      "scriptId":"u71"},
    "b128cd9fd3ce4e069e693800426ef136":{
      "scriptId":"u72"},
    "a8eabf7e20c847a89369ea918ef2c7af":{
      "scriptId":"u73"},
    "330a7ba2ab6248c4ad540f90bcaa341c":{
      "scriptId":"u74"},
    "eb416d8126b4464d92cbfac9105fd049":{
      "scriptId":"u75"},
    "b658e46706de4f399f4b00389f82f642":{
      "scriptId":"u76"},
    "7e76c872ed6841f5aaddaabcf99c02b3":{
      "scriptId":"u77"},
    "d1024700067c445588923ac6c2edec6b":{
      "scriptId":"u78"},
    "c20fd73c576e48638d3ae15ded17ae2e":{
      "scriptId":"u79"},
    "4c98eab81a7f4b319aad35d0c0cb4225":{
      "scriptId":"u80"}}});