$axure.loadCurrentPage({
  "url":"usluga.html",
  "generationDate":new Date(1399457451941.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a79c2e41c463435c844fde5b52b5f7de",
    "type":"Axure:Page",
    "name":"Usluga",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6f4865d589704157adbadef2de19bf2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":462,
              "y":231},
            "size":{
              "width":500,
              "height":168}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44637db141864b629c3f771cdf3e0bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":462,
                  "y":231},
                "size":{
                  "width":500,
                  "height":168}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e06cbc6eead486b8c31ff72f2acbd59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":230,
              "y":470},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce57c04dfc9446308a0f55fcc4e200a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":230,
                  "y":470},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d42c1919384deda692986dbe72c189",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":144},
            "size":{
              "width":308,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e07091a9065457fad9b8efb8582aee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":144},
                "size":{
                  "width":308,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80f1a6d9759e4bc9a768000fc931cece",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":520},
            "size":{
              "width":720,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"811cdb26b4304fa6ac90c3c2fbe1b41a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":520},
                "size":{
                  "width":720,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcb0e9c4cbd440dfb93fcf6984702cf6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":228,
              "y":220},
            "size":{
              "width":190,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe90675009d47c0adbeebb8ce94d168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":228,
                  "y":220},
                "size":{
                  "width":190,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u10.png"}},
{
          "id":"39f4c7426ba54b478ac110f6c50a86bf",
          "label":"dropmenu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":230,
              "y":116},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0ca1743513ec4c328ce59208c5d65d28",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4b938a12503f45329cee43cb67429f6f",
                  "label":"",
                  "parentDynamicPanel":"39f4c7426ba54b478ac110f6c50a86bf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":150,
                      "height":134}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9caf05a16258424692d0c035b4dabe9e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"39f4c7426ba54b478ac110f6c50a86bf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":150,
                          "height":134}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/usluga/u11.png"}},
{
                  "id":"1ffe9b00c5c84c9aa9973667c96736de",
                  "label":"",
                  "parentDynamicPanel":"39f4c7426ba54b478ac110f6c50a86bf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "lineSpacing":"18px",
                    "location":{
                      "x":10,
                      "y":11},
                    "size":{
                      "width":140,
                      "height":109}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34f8e9eb6269490e856b20d071a3cdb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"39f4c7426ba54b478ac110f6c50a86bf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "lineSpacing":"18px",
                        "location":{
                          "x":10,
                          "y":11},
                        "size":{
                          "width":140,
                          "height":109}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"ee6b99f58fd4454c8217ff2e0326f038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":90},
            "size":{
              "width":130,
              "height":26},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3e90f03fa0b4837a78b5b611601c268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":90},
                "size":{
                  "width":130,
                  "height":26},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show dropmenu",
                      "objectsToFades":[{
                          "objectPath":["39f4c7426ba54b478ac110f6c50a86bf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide dropmenu",
                      "objectsToFades":[{
                          "objectPath":["39f4c7426ba54b478ac110f6c50a86bf"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/product_1/u56.png"}},
{
          "id":"10abbf1a11714c2abeced0e8acaa6766",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"cd5b058f5c2d4658b7b95ab2beca71d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":229.999969482422,
              "y":1298},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d739fcd7c0854760bb919391f4f1c393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229.999969482422,
                  "y":1298},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u67.png"}},
{
          "id":"b26a7613cb6c4c3fafff07d7237fbe4e",
          "label":"menu_left",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":190,
              "height":1110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fadd692e76e440eb816dcdc310965e91",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"17bbde07072a4fbd86cf43ba802aceb5",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":190,
                      "height":1140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8774b09577dd4aad98e362a023993e4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":190,
                          "height":1140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"8252c59deaa949a395ae30140efcacd6",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":276},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4e9877bd2054415bc0ced5e6d2d3c2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":276},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"294777c3255f4f6f96ae2f5290c0771a",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":179},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec7b715672de4e7297ef85b34d606ebb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":179},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"72546e7560d54c3ba6cb42956510c6c9",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":133},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af12d96b83ad4cfd9240687df9a86717",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":133},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"4fbb743010644412b3ea75c8c40bdfbf",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":320},
                    "size":{
                      "width":108,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b0fee6cb30349cb831a84d9d9e6fb61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":320},
                        "size":{
                          "width":108,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"aaa8b56c23cb461f8f5b2a105d987fd6",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":25},
                    "size":{
                      "width":163,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73eef82bc4764e8490a0f8885bafe79d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":25},
                        "size":{
                          "width":163,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u28.png"}},
{
                  "id":"0bd900b93c64493f8353baaaab671664",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":228},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"914f6863d8864098875e0a85ea51e087",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":228},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"4dd016d1234e4f37bc174d6f74217fe5",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":122,
                      "y":315},
                    "size":{
                      "width":18,
                      "height":18},
                    "rotation":"270",
                    "textRotation":"270",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a97b609268f4a0fbd0c7d6972fae52e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":122,
                          "y":315},
                        "size":{
                          "width":18,
                          "height":18},
                        "rotation":"270",
                        "textRotation":"270",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u35.png"}},
{
                  "id":"50543e5b98b245559dcdc98480a96456",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":127,
                      "y":316},
                    "size":{
                      "width":8,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a09ae5bb7954934beb45c6e6719fb55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":127,
                          "y":316},
                        "size":{
                          "width":8,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"14dea0a5e3474e09b11d2df565b51a72",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":512},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51a7753285b84ee0b4086425d10a43fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":512},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Vacancy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"vacancy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"c5ebdb4593b34e67a8d90ff67a018ca9",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":471},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd6aee1899c9423aa9028b64d095afc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":471},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Company in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"company.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"f763ab84f135455197699211eba93844",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":594},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"4b412123ea454cc1bdfbc16d1549fdf0",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"a73705ebbac946b8a50989fcd000e43d",
                          "label":"",
                          "parentDynamicPanel":"f763ab84f135455197699211eba93844",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":139,
                              "height":63}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8ddad2b2369c4debb0f2b35b2dc76947",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f763ab84f135455197699211eba93844",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":139,
                                  "height":63}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/index/u31.png"}}]}]},
{
                  "id":"2f0d31f4c73e452883ef3395cefa83cb",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":429},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0841da91bf4545939a45ccc40ec9d019",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":429},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Spravochnik in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"spravochnik.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"215e781097f64ae9ad9c2785f92e43f3",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":388},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50eae0fd6f17428d8fc2282442b10da0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":388},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Calculator in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"calculator.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"ab0637ac1abe42e4b5590bf4dcc4e187",
                  "label":"",
                  "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":553},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b34ce269760d4c13b3512ef5a17da163",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b26a7613cb6c4c3fafff07d7237fbe4e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":553},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Contacts_1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"contacts_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"57e90d6da3e8404cb2a25effa895542b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":229.999969482422,
              "y":773},
            "size":{
              "width":720,
              "height":908},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37694604e6e04b4aaf5a8b814051c2d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":229.999969482422,
                  "y":773},
                "size":{
                  "width":720,
                  "height":908},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1_1/u0.png"}},
{
          "id":"a9ae6066fff94991b9475cc773b8419f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":229.999969482422,
              "y":730},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b6acf67aac5467faa18a163f391c3a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229.999969482422,
                  "y":730},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e81ff6817044c7da4a1bcd48fe43e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":249.999969482422,
              "y":825},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1bf828fdcdd4839a487aa79ee81690c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":249.999969482422,
                  "y":825},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dddc784968914fa9bdf545461b87e684",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":251.999969482422,
              "y":890},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"2de4b91ad8be464882d3344b023c016e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":251.999969482422,
              "y":977},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"e44eaf4aa2a54b739b9c97cae4e76081",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":575,
              "y":977},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"40863b39892646a09841cdd14723c409",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":575,
              "y":890},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"b740ebfcf6984ebda6e39595b302601a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":1588},
            "size":{
              "width":141,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"9c333d59a9554b5da17f006dd1661cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249.999969482422,
              "y":1198},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d199dd6adec54c50b3a9a925fd2886a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249.999969482422,
                  "y":1198},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"e3e93373e4f04150ab8598b2e5e3b7bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":256.999969482422,
              "y":1198},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e02b8016b7b24ebfa5a22169aa01febb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":256.999969482422,
                  "y":1198},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"005bc38aa5d8411fa10ef7c266b47a65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":289.999969482422,
              "y":1205},
            "size":{
              "width":173,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b889cb6fa394f38ad145ccba7f3121d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289.999969482422,
                  "y":1205},
                "size":{
                  "width":173,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1828eda7f39349d98517fda44fb11ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":249.999969482422,
              "y":1054},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"712113007a4d40989a9e842fa1d5ce9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":249.999969482422,
                  "y":1054},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"480becba268449e69dd16aea6e586b99",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":249.999969482422,
              "y":1124},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"e62e7000b2594c0696f9d659e9801bd1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":1124},
            "size":{
              "width":166,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"56042857f5ca49ea85c74f9948f23de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249.999969482422,
              "y":1588},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dcf3bb4f23c48d6a8bfa1245957c3ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249.999969482422,
                  "y":1588},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"c9235bdf26514786bbc2f62e18c36c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":256.999969482422,
              "y":1588},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"448f917fa447450ca2d6eeebde7b21a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":256.999969482422,
                  "y":1588},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4b4ea97026643fd87e31ab9cd91adac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":289.999969482422,
              "y":1595},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b05307ccccef4962b820f56e6834f5f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289.999969482422,
                  "y":1595},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dc26122bbe349558445e96df31d8885",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":770,
              "y":1124},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"480bc32c96894a44b5b4068bfaa3a5a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":249.999969482422,
              "y":1261},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310c8d27a43d4ee6a9ae71d35d1173b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":249.999969482422,
                  "y":1261},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69654ed0047d4e4f945d579ee3f6c0d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":429.999969482422,
              "y":1588},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"004bc0252cda4e4f9f74e2e17ce32e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429.999969482422,
                  "y":1588},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"b6a71442a367499bb2ae4b0e525135ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":436.999969482422,
              "y":1588},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2072f5ecdbbd476384a157e658a3916b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":436.999969482422,
                  "y":1588},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a76e40567684147b496ecbeeb377e87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":469.999969482422,
              "y":1595},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aea13d85d264424a8339848ce421de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469.999969482422,
                  "y":1595},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7119a45e6e21472b9c3ed62b129942f3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":251.999969482422,
              "y":1439},
            "size":{
              "width":599,
              "height":112}},
          "adaptiveStyles":{
}},
{
          "id":"409b7e0beb254d8c90ffff48f5d9c0a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":256.999969482422,
              "y":1459},
            "size":{
              "width":574,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a53694dc2aa4b74ace19e39a3746de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":256.999969482422,
                  "y":1459},
                "size":{
                  "width":574,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"375cb09eb9924086b279338a7b88f1aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":249.999969482422,
              "y":1373},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d33555117004022885acca3d28d4584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":249.999969482422,
                  "y":1373},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6112b489bba44f0bc9fc167c6b368f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1740},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b30ff92cd94ba2a8cea0db2005d517",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1740},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u67.png"}},
{
          "id":"f6e2bbfb9dc4463a8ae81fa87a04831f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":1311},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5908b6bc4e014a89be8b32f0dcd7fa14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":1311},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"dac8edc6973044a6a99535ac313d5f2c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":1311},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4852b04f4d347af80ab1cea790c548c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":1311},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6b88ac7e3b3741ef8ffda89a44e59371",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":1311},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f612ca0ea1b4617866aa16b631bd667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":1311},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"55e50113fc694c80ab7e5c3d12d9e049",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1311},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2a3e2e03e4947e8b59198c4dc364b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":1311},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"273c39a9e0d745c1b9429880b219756e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":618,
              "y":1311},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3b50c0765ce4eeda1d60261983e670f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":618,
                  "y":1311},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "6f4865d589704157adbadef2de19bf2b":{
      "scriptId":"u0"},
    "44637db141864b629c3f771cdf3e0bfe":{
      "scriptId":"u1"},
    "1e06cbc6eead486b8c31ff72f2acbd59":{
      "scriptId":"u2"},
    "ce57c04dfc9446308a0f55fcc4e200a1":{
      "scriptId":"u3"},
    "b4d42c1919384deda692986dbe72c189":{
      "scriptId":"u4"},
    "4e07091a9065457fad9b8efb8582aee0":{
      "scriptId":"u5"},
    "80f1a6d9759e4bc9a768000fc931cece":{
      "scriptId":"u6"},
    "811cdb26b4304fa6ac90c3c2fbe1b41a":{
      "scriptId":"u7"},
    "fcb0e9c4cbd440dfb93fcf6984702cf6":{
      "scriptId":"u8"},
    "6fe90675009d47c0adbeebb8ce94d168":{
      "scriptId":"u9"},
    "39f4c7426ba54b478ac110f6c50a86bf":{
      "scriptId":"u10"},
    "4b938a12503f45329cee43cb67429f6f":{
      "scriptId":"u11"},
    "9caf05a16258424692d0c035b4dabe9e":{
      "scriptId":"u12"},
    "1ffe9b00c5c84c9aa9973667c96736de":{
      "scriptId":"u13"},
    "34f8e9eb6269490e856b20d071a3cdb6":{
      "scriptId":"u14"},
    "ee6b99f58fd4454c8217ff2e0326f038":{
      "scriptId":"u15"},
    "c3e90f03fa0b4837a78b5b611601c268":{
      "scriptId":"u16"},
    "10abbf1a11714c2abeced0e8acaa6766":{
      "scriptId":"u17",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u18"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u19"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u20"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u21"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u22"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u23"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u24"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u25"}},
    "cd5b058f5c2d4658b7b95ab2beca71d6":{
      "scriptId":"u26"},
    "d739fcd7c0854760bb919391f4f1c393":{
      "scriptId":"u27"},
    "b26a7613cb6c4c3fafff07d7237fbe4e":{
      "scriptId":"u28"},
    "17bbde07072a4fbd86cf43ba802aceb5":{
      "scriptId":"u29"},
    "8774b09577dd4aad98e362a023993e4b":{
      "scriptId":"u30"},
    "8252c59deaa949a395ae30140efcacd6":{
      "scriptId":"u31"},
    "a4e9877bd2054415bc0ced5e6d2d3c2c":{
      "scriptId":"u32"},
    "294777c3255f4f6f96ae2f5290c0771a":{
      "scriptId":"u33"},
    "ec7b715672de4e7297ef85b34d606ebb":{
      "scriptId":"u34"},
    "72546e7560d54c3ba6cb42956510c6c9":{
      "scriptId":"u35"},
    "af12d96b83ad4cfd9240687df9a86717":{
      "scriptId":"u36"},
    "4fbb743010644412b3ea75c8c40bdfbf":{
      "scriptId":"u37"},
    "4b0fee6cb30349cb831a84d9d9e6fb61":{
      "scriptId":"u38"},
    "aaa8b56c23cb461f8f5b2a105d987fd6":{
      "scriptId":"u39"},
    "73eef82bc4764e8490a0f8885bafe79d":{
      "scriptId":"u40"},
    "0bd900b93c64493f8353baaaab671664":{
      "scriptId":"u41"},
    "914f6863d8864098875e0a85ea51e087":{
      "scriptId":"u42"},
    "4dd016d1234e4f37bc174d6f74217fe5":{
      "scriptId":"u43"},
    "6a97b609268f4a0fbd0c7d6972fae52e":{
      "scriptId":"u44"},
    "50543e5b98b245559dcdc98480a96456":{
      "scriptId":"u45"},
    "4a09ae5bb7954934beb45c6e6719fb55":{
      "scriptId":"u46"},
    "14dea0a5e3474e09b11d2df565b51a72":{
      "scriptId":"u47"},
    "51a7753285b84ee0b4086425d10a43fd":{
      "scriptId":"u48"},
    "c5ebdb4593b34e67a8d90ff67a018ca9":{
      "scriptId":"u49"},
    "dd6aee1899c9423aa9028b64d095afc0":{
      "scriptId":"u50"},
    "f763ab84f135455197699211eba93844":{
      "scriptId":"u51"},
    "a73705ebbac946b8a50989fcd000e43d":{
      "scriptId":"u52"},
    "8ddad2b2369c4debb0f2b35b2dc76947":{
      "scriptId":"u53"},
    "2f0d31f4c73e452883ef3395cefa83cb":{
      "scriptId":"u54"},
    "0841da91bf4545939a45ccc40ec9d019":{
      "scriptId":"u55"},
    "215e781097f64ae9ad9c2785f92e43f3":{
      "scriptId":"u56"},
    "50eae0fd6f17428d8fc2282442b10da0":{
      "scriptId":"u57"},
    "ab0637ac1abe42e4b5590bf4dcc4e187":{
      "scriptId":"u58"},
    "b34ce269760d4c13b3512ef5a17da163":{
      "scriptId":"u59"},
    "57e90d6da3e8404cb2a25effa895542b":{
      "scriptId":"u60"},
    "37694604e6e04b4aaf5a8b814051c2d7":{
      "scriptId":"u61"},
    "a9ae6066fff94991b9475cc773b8419f":{
      "scriptId":"u62"},
    "9b6acf67aac5467faa18a163f391c3a2":{
      "scriptId":"u63"},
    "7e81ff6817044c7da4a1bcd48fe43e30":{
      "scriptId":"u64"},
    "b1bf828fdcdd4839a487aa79ee81690c":{
      "scriptId":"u65"},
    "dddc784968914fa9bdf545461b87e684":{
      "scriptId":"u66"},
    "2de4b91ad8be464882d3344b023c016e":{
      "scriptId":"u67"},
    "e44eaf4aa2a54b739b9c97cae4e76081":{
      "scriptId":"u68"},
    "40863b39892646a09841cdd14723c409":{
      "scriptId":"u69"},
    "b740ebfcf6984ebda6e39595b302601a":{
      "scriptId":"u70"},
    "9c333d59a9554b5da17f006dd1661cae":{
      "scriptId":"u71"},
    "d199dd6adec54c50b3a9a925fd2886a5":{
      "scriptId":"u72"},
    "e3e93373e4f04150ab8598b2e5e3b7bd":{
      "scriptId":"u73"},
    "e02b8016b7b24ebfa5a22169aa01febb":{
      "scriptId":"u74"},
    "005bc38aa5d8411fa10ef7c266b47a65":{
      "scriptId":"u75"},
    "8b889cb6fa394f38ad145ccba7f3121d":{
      "scriptId":"u76"},
    "1828eda7f39349d98517fda44fb11ed1":{
      "scriptId":"u77"},
    "712113007a4d40989a9e842fa1d5ce9a":{
      "scriptId":"u78"},
    "480becba268449e69dd16aea6e586b99":{
      "scriptId":"u79"},
    "e62e7000b2594c0696f9d659e9801bd1":{
      "scriptId":"u80"},
    "56042857f5ca49ea85c74f9948f23de7":{
      "scriptId":"u81"},
    "2dcf3bb4f23c48d6a8bfa1245957c3ea":{
      "scriptId":"u82"},
    "c9235bdf26514786bbc2f62e18c36c73":{
      "scriptId":"u83"},
    "448f917fa447450ca2d6eeebde7b21a9":{
      "scriptId":"u84"},
    "a4b4ea97026643fd87e31ab9cd91adac":{
      "scriptId":"u85"},
    "b05307ccccef4962b820f56e6834f5f7":{
      "scriptId":"u86"},
    "8dc26122bbe349558445e96df31d8885":{
      "scriptId":"u87"},
    "480bc32c96894a44b5b4068bfaa3a5a9":{
      "scriptId":"u88"},
    "310c8d27a43d4ee6a9ae71d35d1173b2":{
      "scriptId":"u89"},
    "69654ed0047d4e4f945d579ee3f6c0d3":{
      "scriptId":"u90"},
    "004bc0252cda4e4f9f74e2e17ce32e60":{
      "scriptId":"u91"},
    "b6a71442a367499bb2ae4b0e525135ce":{
      "scriptId":"u92"},
    "2072f5ecdbbd476384a157e658a3916b":{
      "scriptId":"u93"},
    "4a76e40567684147b496ecbeeb377e87":{
      "scriptId":"u94"},
    "9aea13d85d264424a8339848ce421de2":{
      "scriptId":"u95"},
    "7119a45e6e21472b9c3ed62b129942f3":{
      "scriptId":"u96"},
    "409b7e0beb254d8c90ffff48f5d9c0a3":{
      "scriptId":"u97"},
    "9a53694dc2aa4b74ace19e39a3746de2":{
      "scriptId":"u98"},
    "375cb09eb9924086b279338a7b88f1aa":{
      "scriptId":"u99"},
    "8d33555117004022885acca3d28d4584":{
      "scriptId":"u100"},
    "a6112b489bba44f0bc9fc167c6b368f2":{
      "scriptId":"u101"},
    "00b30ff92cd94ba2a8cea0db2005d517":{
      "scriptId":"u102"},
    "f6e2bbfb9dc4463a8ae81fa87a04831f":{
      "scriptId":"u103"},
    "5908b6bc4e014a89be8b32f0dcd7fa14":{
      "scriptId":"u104"},
    "dac8edc6973044a6a99535ac313d5f2c":{
      "scriptId":"u105"},
    "b4852b04f4d347af80ab1cea790c548c":{
      "scriptId":"u106"},
    "6b88ac7e3b3741ef8ffda89a44e59371":{
      "scriptId":"u107"},
    "0f612ca0ea1b4617866aa16b631bd667":{
      "scriptId":"u108"},
    "55e50113fc694c80ab7e5c3d12d9e049":{
      "scriptId":"u109"},
    "f2a3e2e03e4947e8b59198c4dc364b2d":{
      "scriptId":"u110"},
    "273c39a9e0d745c1b9429880b219756e":{
      "scriptId":"u111"},
    "a3b50c0765ce4eeda1d60261983e670f":{
      "scriptId":"u112"}}});