$axure.loadCurrentPage({
  "url":"information.html",
  "generationDate":new Date(1399457447732.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2be9018066994d3598da334dd2a7a8ec",
    "type":"Axure:Page",
    "name":"Information",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec9dc7c4da6441f8bd0485b3cc868cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":111,
              "y":121},
            "size":{
              "width":352,
              "height":359},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1b14f6963d94af2970144f280286402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":111,
                  "y":121},
                "size":{
                  "width":352,
                  "height":359},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/information/u0.png"}},
{
          "id":"af134c4a050f4006bbb544b573d6fad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":128,
              "y":359},
            "size":{
              "width":315,
              "height":98},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67a9534861bc44228739f90dfb17a1f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":128,
                  "y":359},
                "size":{
                  "width":315,
                  "height":98},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/information/u2.png"}},
{
          "id":"333a5b8e633d4876b89e2aa28f6c041c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":189,
              "y":392},
            "size":{
              "width":219,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7ad8c64c4f46b49625b6c028f489de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":189,
                  "y":392},
                "size":{
                  "width":219,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2c9826778744bb1b695f3da75229783",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "lineSpacing":"18px",
            "location":{
              "x":131,
              "y":139},
            "size":{
              "width":312,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2130cc631d0d4bb4b55bf0237e047bc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "lineSpacing":"18px",
                "location":{
                  "x":131,
                  "y":139},
                "size":{
                  "width":312,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4da42b393248473dbd8084c3db2b0f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":156,
              "y":232},
            "size":{
              "width":307,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c20bafbb2c7a4fa1b70256b92d4b3779",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":156,
                  "y":232},
                "size":{
                  "width":307,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe34e81bf2724cbeb616beda0ca46d8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "lineSpacing":"20px",
            "location":{
              "x":156,
              "y":195},
            "size":{
              "width":290,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6987f59ebbf7413c84ac689bfe9bac65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "lineSpacing":"20px",
                "location":{
                  "x":156,
                  "y":195},
                "size":{
                  "width":290,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"864f66a7fd674c35a15226e93173f860",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "underline":true,
            "lineSpacing":"20px",
            "location":{
              "x":156,
              "y":312},
            "size":{
              "width":154,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be3af8782cb444193492fc5ea1c241d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "underline":true,
                "lineSpacing":"20px",
                "location":{
                  "x":156,
                  "y":312},
                "size":{
                  "width":154,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open https://drive.google.com/?tab=wo&amp;authuser=0#folders/0B6vyQtaqjBJFU0wyZmx6R3FfYzQ in Current Window",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://drive.google.com/?tab=wo&authuser=0#folders/0B6vyQtaqjBJFU0wyZmx6R3FfYzQ",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1923b3c0c7924984ba04ad1621eb69ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":109,
              "y":500},
            "size":{
              "width":349,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65240071fca3422f96f0ce436ff3d408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":109,
                  "y":500},
                "size":{
                  "width":349,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25c4704657834fb2a408a39c2808c28d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":547},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1134ebffdc6844adb86c132897a6fcd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":547},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/information/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec9dc7c4da6441f8bd0485b3cc868cc1":{
      "scriptId":"u0"},
    "f1b14f6963d94af2970144f280286402":{
      "scriptId":"u1"},
    "af134c4a050f4006bbb544b573d6fad1":{
      "scriptId":"u2"},
    "67a9534861bc44228739f90dfb17a1f4":{
      "scriptId":"u3"},
    "333a5b8e633d4876b89e2aa28f6c041c":{
      "scriptId":"u4"},
    "4f7ad8c64c4f46b49625b6c028f489de":{
      "scriptId":"u5"},
    "c2c9826778744bb1b695f3da75229783":{
      "scriptId":"u6"},
    "2130cc631d0d4bb4b55bf0237e047bc6":{
      "scriptId":"u7"},
    "4da42b393248473dbd8084c3db2b0f1c":{
      "scriptId":"u8"},
    "c20bafbb2c7a4fa1b70256b92d4b3779":{
      "scriptId":"u9"},
    "fe34e81bf2724cbeb616beda0ca46d8d":{
      "scriptId":"u10"},
    "6987f59ebbf7413c84ac689bfe9bac65":{
      "scriptId":"u11"},
    "864f66a7fd674c35a15226e93173f860":{
      "scriptId":"u12"},
    "0be3af8782cb444193492fc5ea1c241d":{
      "scriptId":"u13"},
    "1923b3c0c7924984ba04ad1621eb69ca":{
      "scriptId":"u14"},
    "65240071fca3422f96f0ce436ff3d408":{
      "scriptId":"u15"},
    "25c4704657834fb2a408a39c2808c28d":{
      "scriptId":"u16"},
    "1134ebffdc6844adb86c132897a6fcd3":{
      "scriptId":"u17"}}});