$axure.loadCurrentPage({
  "url":"product_1_1.html",
  "generationDate":new Date(1399457451603.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6624cdccdd9c464f9815da4ae434f58f",
    "type":"Axure:Page",
    "name":"Product_1.1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"77130b0e584143cc8a7920ab8d191579",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":762},
            "size":{
              "width":720,
              "height":908},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441e0a766fbb492cbfd96d2534658ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":762},
                "size":{
                  "width":720,
                  "height":908},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1_1/u0.png"}},
{
          "id":"6f4865d589704157adbadef2de19bf2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "lineSpacing":"28px",
            "location":{
              "x":462,
              "y":250},
            "size":{
              "width":500,
              "height":123}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44637db141864b629c3f771cdf3e0bfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "lineSpacing":"28px",
                "location":{
                  "x":462,
                  "y":250},
                "size":{
                  "width":500,
                  "height":123}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e06cbc6eead486b8c31ff72f2acbd59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":719},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce57c04dfc9446308a0f55fcc4e200a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":719},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Link in Current Window",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d42c1919384deda692986dbe72c189",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":144},
            "size":{
              "width":310,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e07091a9065457fad9b8efb8582aee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":144},
                "size":{
                  "width":310,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80f1a6d9759e4bc9a768000fc931cece",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":457},
            "size":{
              "width":720,
              "height":226}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"811cdb26b4304fa6ac90c3c2fbe1b41a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":457},
                "size":{
                  "width":720,
                  "height":226}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcb0e9c4cbd440dfb93fcf6984702cf6",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":228,
              "y":220},
            "size":{
              "width":190,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe90675009d47c0adbeebb8ce94d168",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":228,
                  "y":220},
                "size":{
                  "width":190,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u10.png"}},
{
          "id":"a4390f68ae9844ce92fdd41180b2bd7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":250,
              "y":814},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16512586dc0405191ec0dbdc8433532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":250,
                  "y":814},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10abbf1a11714c2abeced0e8acaa6766",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":-1}},
          "adaptiveStyles":{
},
          "masterId":"e3e3753783f84b8e942cb72a489ef35b"},
{
          "id":"36687c7be8174d34825403b7febc245f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":2310},
            "size":{
              "width":200,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6725d8608674901ac63ea949d740c13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":2310},
                "size":{
                  "width":200,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/product_1/u67.png"}},
{
          "id":"526b2e838d7b41d08799d53d09b5714f",
          "label":"menu_left",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":190,
              "height":1110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":0,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e791eb86615f45c8aa2d36ac21c42840",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3119a03f34ff455fb2491bdf582f6e44",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":190,
                      "height":1140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f726aed743a48b7ae30997c4271d2a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":190,
                          "height":1140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u14.png"}},
{
                  "id":"ccb5defd098a43b9a4a14eeefc0a6385",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":276},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13ce9c19b9664825864db50215cc6a20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":276},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"d59638057be24eff93f605a2e5f7c30c",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":179},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1cee638e3414bf180d67749f0bcdbaa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":179},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"be9405a519ee439bbe578256750ce482",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":133},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eae46525ba194fd887f33f196791989e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":133},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"eed5a864b372400b9500208241c46e5e",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":320},
                    "size":{
                      "width":108,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cca4dc16e73c40dcbfce5392e42f01ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":320},
                        "size":{
                          "width":108,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"bc1c006c30e34b67b87b0ede3c89b1bf",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":25},
                    "size":{
                      "width":163,
                      "height":75}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7ab98132364495eb0ca2b419c3b73ff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":25},
                        "size":{
                          "width":163,
                          "height":75}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u28.png"}},
{
                  "id":"2be4cd349cd14a8aa5baefdd6ce1bdaf",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Полужирный', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":228},
                    "size":{
                      "width":92,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87e154896cf4460eaec7dafe782c8e46",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Полужирный', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":228},
                        "size":{
                          "width":92,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"scrollToWidget",
                              "description":"Scroll to Widget"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"26a7614fbf3b480a8c8e63cb37d2fc37",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":122,
                      "y":315},
                    "size":{
                      "width":18,
                      "height":18},
                    "rotation":"270",
                    "textRotation":"270",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7d00349285e4b5997386260b2025380",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":122,
                          "y":315},
                        "size":{
                          "width":18,
                          "height":18},
                        "rotation":"270",
                        "textRotation":"270",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u35.png"}},
{
                  "id":"ecd78e4aa01c43df87d1a4e693029571",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":127,
                      "y":316},
                    "size":{
                      "width":8,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7256c94b0c6a4450b7090eaaa02dce31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":127,
                          "y":316},
                        "size":{
                          "width":8,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"adf5df376e6b4906849f98e2f4e95a46",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":512},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c72c280dd6c443d955d1cd0417f77e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":512},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Vacancy in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"vacancy.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"93b1e7f46b0946aba9b917b59097d447",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":471},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91c34c6960d94c66a27f9c3c6f27a35c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":471},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Company in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"company.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"3bddeb27eff841c18d0dcd7ee6ca2a7e",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":594},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"8364d3d8a89646bea5375db86031daf4",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"dc29d34ce95e4e4ab6081ce2af74bbbf",
                          "label":"",
                          "parentDynamicPanel":"3bddeb27eff841c18d0dcd7ee6ca2a7e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":139,
                              "height":63}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6124629456a045ecb9423a18f5c33267",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"3bddeb27eff841c18d0dcd7ee6ca2a7e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":139,
                                  "height":63}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/index/u31.png"}}]}]},
{
                  "id":"52689dfc49724e44b30a504ec169a75f",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":429},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"452707ed72c74ee7a99f045bbc115512",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":429},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Spravochnik in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"spravochnik.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"5efedf3bcf114e1598477cdb1c6979e6",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":51,
                      "y":388},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f0412b312b243c0a059d46621d01819",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":51,
                          "y":388},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Calculator in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"calculator.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"dc78624f90174620be2cadcf99288ab1",
                  "label":"",
                  "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true},
                      "selected":{
                        "underline":true}},
                    "location":{
                      "x":50,
                      "y":553},
                    "size":{
                      "width":90,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b33b81338a84a1999c7467d454588a9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"526b2e838d7b41d08799d53d09b5714f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true},
                          "selected":{
                            "underline":true}},
                        "location":{
                          "x":50,
                          "y":553},
                        "size":{
                          "width":90,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Contacts_1 in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"contacts_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "selected~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
          "id":"a707cd8b88f7429ca3ea5c0cf2a3af37",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":252,
              "y":879},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"e615b264f0ed4605b4e4a9f080593a18",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":252,
              "y":966},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"052bff966af04e1db4c165e3cc8d6fde",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":575,
              "y":966},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"581e08a08d6a4135abdb9ba63197058f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":575,
              "y":879},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"dddcd3b1f56748978da99eb9a8a67874",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":1577},
            "size":{
              "width":141,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"768e73f23dce4222b91a2ba987f036f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":1187},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e9cde68a6d948d9b536d0d3f320526d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":1187},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"17aa0d47a200440f9d97378e1300ea78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":257,
              "y":1187},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b475f7fe6df40d2bd377d30d6620630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":257,
                  "y":1187},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8faf40fd9b414476b7a9189d85191173",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":1194},
            "size":{
              "width":173,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e50fdf983d040729a8779dda72b685f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":1194},
                "size":{
                  "width":173,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e816d13956354eae9b53b4bc30b0de75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":250,
              "y":1043},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bf4843481cf43c7bb39cdedb98d91b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":250,
                  "y":1043},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"233b5976778749979d950a1618b23526",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":1113},
            "size":{
              "width":276,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"fc2550897dfc48fcb665db96ebbdb490",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":1113},
            "size":{
              "width":166,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"e485a2ad862c46139933a22447337930",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":1577},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9857545a3ef6435ab56b6c58062b4d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":1577},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"6dcef5a5d25d4e99b4e984a9772db1b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":257,
              "y":1577},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb68135e0a048758fdaa42bf0f74cde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":257,
                  "y":1577},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"518c733cfa8d4297a5e902f7ee6d3258",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":1584},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d8698433e141e38c547454c57ee67d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":1584},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f95134c348045de85511cf70cc31348",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":770,
              "y":1113},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"9a2df9a9fca042bb9d25a88d884068b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":250,
              "y":1250},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9827dec2df3c4f66a7e3fbe24f671e48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":250,
                  "y":1250},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d9a3a843a12456bad34055c1293c287",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":1577},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b063b49b47d42b19d03be89a708205e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":1577},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u58.png"}},
{
          "id":"6a4ee6a216a4496d8243078ab4e0f5bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":437,
              "y":1577},
            "size":{
              "width":17,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e2abba86d71425cb3ccf01a532a4437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":437,
                  "y":1577},
                "size":{
                  "width":17,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc067b023b0840519bae5aaf6fc1ae39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1584},
            "size":{
              "width":135,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41c7f0850b73463db955694c6765b0c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1584},
                "size":{
                  "width":135,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cfb784c54f6428796e26d36b45610bc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":252,
              "y":1428},
            "size":{
              "width":599,
              "height":112}},
          "adaptiveStyles":{
}},
{
          "id":"7ad3997595f040838230d69c0486fb69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":257,
              "y":1448},
            "size":{
              "width":574,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60c22fec91694995bb897a7cca750157",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":257,
                  "y":1448},
                "size":{
                  "width":574,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"572cb3fda5b64e2fa25fc5993851fa28",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Полужирный', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":250,
              "y":1362},
            "size":{
              "width":530,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fee25d58aa254f26bfc776dcafb3c11c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Полужирный', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":250,
                  "y":1362},
                "size":{
                  "width":530,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"220e1447784a474c982378406226a479",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":85},
            "size":{
              "width":120,
              "height":26},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4747a72c78574d0da9c568b549b8b5c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":85},
                "size":{
                  "width":120,
                  "height":26},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Product_1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"product_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/product_1_1/u92.png"}},
{
          "id":"74c0f9077cb14030bc86644f0d5e51d5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":1300},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f38464334c41a9bb6cc12ba000ce1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":1300},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ad51788e23ce40bc8fdf08c632bbc831",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":1300},
            "size":{
              "width":68,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a91c9fb86a4e58ab6932fe923043f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":1300},
                "size":{
                  "width":68,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c916325dcbbf460a85f55758c139912c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":1300},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b43e194e002b49408b759fb63dde349a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":1300},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"791a4d17bdfd4311bb52291d3418eb16",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":1300},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"925c15132f0b4f0f93830b8b64a538bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":514,
                  "y":1300},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1280181deecf440eb3f6b1cba1c317b4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":622,
              "y":1300},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a20a36c9aac4e73b5473fb0851469fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":622,
                  "y":1300},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "e3e3753783f84b8e942cb72a489ef35b":{
      "packageId":"e3e3753783f84b8e942cb72a489ef35b",
      "type":"Axure:Master",
      "name":"head_content",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"9b84f82d11314d9897dabdb7c9862271",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":-1},
              "size":{
                "width":790,
                "height":54}},
            "adaptiveStyles":{
},
            "fixedHorizontal":"left",
            "fixedMarginHorizontal":190,
            "fixedVertical":"top",
            "fixedMarginVertical":-1,
            "fixedKeepInFront":true,
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"319bd91865384722b62b61a5527dad4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"853d3c3caf1140cda0ca16b7d0ae5723",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":1050,
                        "height":54},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "outerShadow":{
                        "on":false,
                        "offsetX":0,
                        "offsetY":5,
                        "blurRadius":10,
                        "color":{
                          "r":204,
                          "g":204,
                          "b":204,
                          "a":0.549019607843137}}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2a072b9f2d8349029c5ce3e1d2e7dc5b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":1050,
                            "height":54},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "outerShadow":{
                            "on":false,
                            "offsetX":0,
                            "offsetY":5,
                            "blurRadius":10,
                            "color":{
                              "r":204,
                              "g":204,
                              "b":204,
                              "a":0.549019607843137}}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/index/u2.png"}},
{
                    "id":"168b37943c1843c6a8ea5a0b3bb47763",
                    "label":"",
                    "parentDynamicPanel":"9b84f82d11314d9897dabdb7c9862271",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":330,
                        "y":20},
                      "size":{
                        "width":504,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5054fbe5781241aca1422e1cb45714db",
                        "label":"State1",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"b0c00a810bf2472797f1efd4c064c28b",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'Arial Полужирный', 'Arial'",
                              "fontSize":"14px",
                              "fontWeight":"700",
                              "size":{
                                "width":120,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6fba313da2c54f5484964d37e58d04b5",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontName":"'Arial Полужирный', 'Arial'",
                                  "fontSize":"14px",
                                  "fontWeight":"700",
                                  "size":{
                                    "width":120,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"307aa75af9ad4b7db1a9ac55e2aa5c0a",
                            "label":"",
                            "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontSize":"14px",
                              "location":{
                                "x":118,
                                "y":0},
                              "size":{
                                "width":294,
                                "height":22}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"16849d5f660849b2b7da744f5dd802f4",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"168b37943c1843c6a8ea5a0b3bb47763",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"14px",
                                  "location":{
                                    "x":118,
                                    "y":0},
                                  "size":{
                                    "width":294,
                                    "height":22}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]}]}]}]}]}}},
  "objectPaths":{
    "77130b0e584143cc8a7920ab8d191579":{
      "scriptId":"u0"},
    "441e0a766fbb492cbfd96d2534658ce3":{
      "scriptId":"u1"},
    "6f4865d589704157adbadef2de19bf2b":{
      "scriptId":"u2"},
    "44637db141864b629c3f771cdf3e0bfe":{
      "scriptId":"u3"},
    "1e06cbc6eead486b8c31ff72f2acbd59":{
      "scriptId":"u4"},
    "ce57c04dfc9446308a0f55fcc4e200a1":{
      "scriptId":"u5"},
    "b4d42c1919384deda692986dbe72c189":{
      "scriptId":"u6"},
    "4e07091a9065457fad9b8efb8582aee0":{
      "scriptId":"u7"},
    "80f1a6d9759e4bc9a768000fc931cece":{
      "scriptId":"u8"},
    "811cdb26b4304fa6ac90c3c2fbe1b41a":{
      "scriptId":"u9"},
    "fcb0e9c4cbd440dfb93fcf6984702cf6":{
      "scriptId":"u10"},
    "6fe90675009d47c0adbeebb8ce94d168":{
      "scriptId":"u11"},
    "a4390f68ae9844ce92fdd41180b2bd7e":{
      "scriptId":"u12"},
    "d16512586dc0405191ec0dbdc8433532":{
      "scriptId":"u13"},
    "10abbf1a11714c2abeced0e8acaa6766":{
      "scriptId":"u14",
      "9b84f82d11314d9897dabdb7c9862271":{
        "scriptId":"u15"},
      "853d3c3caf1140cda0ca16b7d0ae5723":{
        "scriptId":"u16"},
      "2a072b9f2d8349029c5ce3e1d2e7dc5b":{
        "scriptId":"u17"},
      "168b37943c1843c6a8ea5a0b3bb47763":{
        "scriptId":"u18"},
      "b0c00a810bf2472797f1efd4c064c28b":{
        "scriptId":"u19"},
      "6fba313da2c54f5484964d37e58d04b5":{
        "scriptId":"u20"},
      "307aa75af9ad4b7db1a9ac55e2aa5c0a":{
        "scriptId":"u21"},
      "16849d5f660849b2b7da744f5dd802f4":{
        "scriptId":"u22"}},
    "36687c7be8174d34825403b7febc245f":{
      "scriptId":"u23"},
    "f6725d8608674901ac63ea949d740c13":{
      "scriptId":"u24"},
    "526b2e838d7b41d08799d53d09b5714f":{
      "scriptId":"u25"},
    "3119a03f34ff455fb2491bdf582f6e44":{
      "scriptId":"u26"},
    "1f726aed743a48b7ae30997c4271d2a5":{
      "scriptId":"u27"},
    "ccb5defd098a43b9a4a14eeefc0a6385":{
      "scriptId":"u28"},
    "13ce9c19b9664825864db50215cc6a20":{
      "scriptId":"u29"},
    "d59638057be24eff93f605a2e5f7c30c":{
      "scriptId":"u30"},
    "e1cee638e3414bf180d67749f0bcdbaa":{
      "scriptId":"u31"},
    "be9405a519ee439bbe578256750ce482":{
      "scriptId":"u32"},
    "eae46525ba194fd887f33f196791989e":{
      "scriptId":"u33"},
    "eed5a864b372400b9500208241c46e5e":{
      "scriptId":"u34"},
    "cca4dc16e73c40dcbfce5392e42f01ee":{
      "scriptId":"u35"},
    "bc1c006c30e34b67b87b0ede3c89b1bf":{
      "scriptId":"u36"},
    "a7ab98132364495eb0ca2b419c3b73ff":{
      "scriptId":"u37"},
    "2be4cd349cd14a8aa5baefdd6ce1bdaf":{
      "scriptId":"u38"},
    "87e154896cf4460eaec7dafe782c8e46":{
      "scriptId":"u39"},
    "26a7614fbf3b480a8c8e63cb37d2fc37":{
      "scriptId":"u40"},
    "c7d00349285e4b5997386260b2025380":{
      "scriptId":"u41"},
    "ecd78e4aa01c43df87d1a4e693029571":{
      "scriptId":"u42"},
    "7256c94b0c6a4450b7090eaaa02dce31":{
      "scriptId":"u43"},
    "adf5df376e6b4906849f98e2f4e95a46":{
      "scriptId":"u44"},
    "7c72c280dd6c443d955d1cd0417f77e6":{
      "scriptId":"u45"},
    "93b1e7f46b0946aba9b917b59097d447":{
      "scriptId":"u46"},
    "91c34c6960d94c66a27f9c3c6f27a35c":{
      "scriptId":"u47"},
    "3bddeb27eff841c18d0dcd7ee6ca2a7e":{
      "scriptId":"u48"},
    "dc29d34ce95e4e4ab6081ce2af74bbbf":{
      "scriptId":"u49"},
    "6124629456a045ecb9423a18f5c33267":{
      "scriptId":"u50"},
    "52689dfc49724e44b30a504ec169a75f":{
      "scriptId":"u51"},
    "452707ed72c74ee7a99f045bbc115512":{
      "scriptId":"u52"},
    "5efedf3bcf114e1598477cdb1c6979e6":{
      "scriptId":"u53"},
    "8f0412b312b243c0a059d46621d01819":{
      "scriptId":"u54"},
    "dc78624f90174620be2cadcf99288ab1":{
      "scriptId":"u55"},
    "4b33b81338a84a1999c7467d454588a9":{
      "scriptId":"u56"},
    "a707cd8b88f7429ca3ea5c0cf2a3af37":{
      "scriptId":"u57"},
    "e615b264f0ed4605b4e4a9f080593a18":{
      "scriptId":"u58"},
    "052bff966af04e1db4c165e3cc8d6fde":{
      "scriptId":"u59"},
    "581e08a08d6a4135abdb9ba63197058f":{
      "scriptId":"u60"},
    "dddcd3b1f56748978da99eb9a8a67874":{
      "scriptId":"u61"},
    "768e73f23dce4222b91a2ba987f036f2":{
      "scriptId":"u62"},
    "2e9cde68a6d948d9b536d0d3f320526d":{
      "scriptId":"u63"},
    "17aa0d47a200440f9d97378e1300ea78":{
      "scriptId":"u64"},
    "8b475f7fe6df40d2bd377d30d6620630":{
      "scriptId":"u65"},
    "8faf40fd9b414476b7a9189d85191173":{
      "scriptId":"u66"},
    "5e50fdf983d040729a8779dda72b685f":{
      "scriptId":"u67"},
    "e816d13956354eae9b53b4bc30b0de75":{
      "scriptId":"u68"},
    "3bf4843481cf43c7bb39cdedb98d91b8":{
      "scriptId":"u69"},
    "233b5976778749979d950a1618b23526":{
      "scriptId":"u70"},
    "fc2550897dfc48fcb665db96ebbdb490":{
      "scriptId":"u71"},
    "e485a2ad862c46139933a22447337930":{
      "scriptId":"u72"},
    "9857545a3ef6435ab56b6c58062b4d0b":{
      "scriptId":"u73"},
    "6dcef5a5d25d4e99b4e984a9772db1b7":{
      "scriptId":"u74"},
    "acb68135e0a048758fdaa42bf0f74cde":{
      "scriptId":"u75"},
    "518c733cfa8d4297a5e902f7ee6d3258":{
      "scriptId":"u76"},
    "e3d8698433e141e38c547454c57ee67d":{
      "scriptId":"u77"},
    "0f95134c348045de85511cf70cc31348":{
      "scriptId":"u78"},
    "9a2df9a9fca042bb9d25a88d884068b5":{
      "scriptId":"u79"},
    "9827dec2df3c4f66a7e3fbe24f671e48":{
      "scriptId":"u80"},
    "3d9a3a843a12456bad34055c1293c287":{
      "scriptId":"u81"},
    "0b063b49b47d42b19d03be89a708205e":{
      "scriptId":"u82"},
    "6a4ee6a216a4496d8243078ab4e0f5bb":{
      "scriptId":"u83"},
    "2e2abba86d71425cb3ccf01a532a4437":{
      "scriptId":"u84"},
    "bc067b023b0840519bae5aaf6fc1ae39":{
      "scriptId":"u85"},
    "41c7f0850b73463db955694c6765b0c6":{
      "scriptId":"u86"},
    "9cfb784c54f6428796e26d36b45610bc":{
      "scriptId":"u87"},
    "7ad3997595f040838230d69c0486fb69":{
      "scriptId":"u88"},
    "60c22fec91694995bb897a7cca750157":{
      "scriptId":"u89"},
    "572cb3fda5b64e2fa25fc5993851fa28":{
      "scriptId":"u90"},
    "fee25d58aa254f26bfc776dcafb3c11c":{
      "scriptId":"u91"},
    "220e1447784a474c982378406226a479":{
      "scriptId":"u92"},
    "4747a72c78574d0da9c568b549b8b5c8":{
      "scriptId":"u93"},
    "74c0f9077cb14030bc86644f0d5e51d5":{
      "scriptId":"u94"},
    "96f38464334c41a9bb6cc12ba000ce1a":{
      "scriptId":"u95"},
    "ad51788e23ce40bc8fdf08c632bbc831":{
      "scriptId":"u96"},
    "94a91c9fb86a4e58ab6932fe923043f9":{
      "scriptId":"u97"},
    "c916325dcbbf460a85f55758c139912c":{
      "scriptId":"u98"},
    "b43e194e002b49408b759fb63dde349a":{
      "scriptId":"u99"},
    "791a4d17bdfd4311bb52291d3418eb16":{
      "scriptId":"u100"},
    "925c15132f0b4f0f93830b8b64a538bc":{
      "scriptId":"u101"},
    "1280181deecf440eb3f6b1cba1c317b4":{
      "scriptId":"u102"},
    "4a20a36c9aac4e73b5473fb0851469fb":{
      "scriptId":"u103"}}});